### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by CortexPE** [LeverylTeam/Leveryl#1]
Fixes:
 - Brewing Stands
 - Hoppers
 - Enchanting Table (Just need to show an Inventory)

Implement:
 - Nether
 - All the stuff on "leveryl.yml"

**Comment by XxParkerGamesxX** [comment]
keep up the good work

**Comment by Pizzahaet** [comment]
@XxParkerGamesxX dude why do you even try? The whole fucking developer community knows how fake you are.... You say you can code but instead you come asking everyone to develop something for you.

**Comment by SirOptic** [comment]
Pizza why do you even have a server software if you can't even code skid

**Comment by CortexPE** [comment]
There's a to-do list on the readme... LOL
