### ISSUE TITLE
W10 edition

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [LeverylTeam/Leveryl#10]
I need help.
I set up a server on windows10 PC, but I cant connect.

I see on client list that my server is online, but wen I connect it say, could not load the world.
Can you tell me what I did wrong?

P.S. I just wanna setup a test server.

**Comment by CortexPE** [comment]
MCPE Version?

**Comment by TDMidkwhatisxd** [comment]
1.1.1

**Comment by bioaim4** [comment]
Are you trying to connect using the same device your hosting on?

**Comment by TDMidkwhatisxd** [comment]
yap, but on my tablet cant connect, so I use pc. Idk why.

**Comment by bioaim4** [comment]
Launch Window PowerShell as an administrator and run the following:
CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"

**Comment by TDMidkwhatisxd** [comment]
thanks
