### ISSUE TITLE
Generic Reason

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#100]
When server restarts people can't join it says "Generic Reason"

**Comment by daniktheboss** [comment]
any crash-dumps or errors?

**Comment by CortexPE** [comment]
can you turn on debug mode in pocketmine.yml?
set it to 2

**Comment by tbhDequan** [comment]
I'll send crash dumn

**Comment by tbhDequan** [comment]
No crash dumb just this error, I'll send debug soon though

**Comment by ghost** [comment]
@LolNova Probably it's plugin error.

**Comment by daniktheboss** [comment]
send us your console log when players cant join

**Comment by tbhDequan** [comment]
/21:58:38 [CRITICAL] ErrorException: "Undefined property: pocketmine\Player::$sessionAdapter" (EXCEPTION) in "/src/pocketmine/Player" at line 3980
01.08 23:58:38 [Server] INFO /21:58:38 [NOTICE] Blocked 72.239.201.92 for 5 seconds
