### ISSUE TITLE
error when entering on the server >.<

### ISSUE THREAD

**Issue by asyncthreading** [LeverylTeam/Leveryl#106]
### Issue description
15:43:54 [CRITICAL] Error: "Call to undefined method pocketmine\network\mcpe\protocol\BatchPacket::compress()" (EXCEPTION) in "/src/pocketmine/Server" at line 2017
15:43:54 [CRITICAL] Error: "Call to undefined method pocketmine\network\mcpe\protocol\BatchPacket::compress()" (EXCEPTION) in "/src/pocketmine/Server" at line 2017

### Steps to reproduce the issue
1. Clone the latest source from github, start the server and connect to the server, it will show up the error then stop the server.

### OS and versions
* Leveryl Version:Latest
* PHP Version:7.0.2
* Server OS:Leveryl
* Game version: PE 
* Game OS: Android

### Plugins
Clean server.

### Crashdump, backtrace or other files
Leveryl Crash Dump Tue Aug 1 15:51:15 CEST 2017

Error: Call to undefined method pocketmine\network\mcpe\protocol\BatchPacket::compress()
File: /src/pocketmine/Server
Line: 2017
Type: notice

Code:
[2008] 			} else {
[2009] 				$compressionLevel = 0; //Do not compress packets under the threshold
[2010] 				$forceSync = true;
[2011] 			}
[2012] 
[2013] 			if(!$forceSync and !$immediate and $this->networkCompressionAsync) {
[2014] 				$task = new CompressBatchedTask($pk, $targets, $compressionLevel);
[2015] 				$this->getScheduler()->scheduleAsyncTask($task);
[2016] 			} else {
[2017] 				$pk->compress($compressionLevel);
[2018] 				$this->broadcastPacketsCallback($pk, $targets, $immediate);
[2019] 			}
[2020] 		}
[2021] 
[2022] 		Timings::$playerNetworkTimer->stopTiming();
[2023] 	}
[2024] 
[2025] 	public function broadcastPacketsCallback(BatchPacket $pk, array $identifiers, bool $immediate = false)
[2026] 	{
[2027] 		if(!$pk->isEncoded) {

Backtrace:
#0 /src/pocketmine/network/mcpe/RakLibInterface(261): pocketmine\Server->batchPackets(array Array(), array Array(), boolean 1, boolean 1)
#1 /src/pocketmine/Player(1251): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\DisconnectPacket object, boolean , boolean 1)
#2 /src/pocketmine/Player(4257): pocketmine\Player->directDataPacket(pocketmine\network\mcpe\protocol\DisconnectPacket object)
#3 /src/pocketmine/Server(2498): pocketmine\Player->close(string , string Login timeout)
#4 /src/pocketmine/Server(2672): pocketmine\Server->checkTickUpdates(integer 1126, double 1501595474.9532)
#5 /src/pocketmine/Server(2420): pocketmine\Server->tick()
#6 /src/pocketmine/Server(2296): pocketmine\Server->tickProcessor()
#7 /src/pocketmine/Server(1832): pocketmine\Server->start()
#8 /src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/champv2/, string /root/champv2/, string /root/champv2/plugins/)

Leveryl version: 1.0 #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux play 2.6.32-48-pve #1 SMP Fri Dec 23 10:22:54 CET 2016 x86_64
PHP Version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWm1v20a2/iuzcoC1L0RZpCy/KHAAr+NsAyStb+0gH6pFMCJHEmuSw3JI29oi//0+55whRSt2
0d5dYPdDUzQV5+XMeT/PmemvgzrNzWAWTsfh9Gx6dDIdDjLt6quqstVg9uug3pSYHhS2TmMzGA5y
45xe0dClzjJVW9UUiVmmhUlUbuq1TVRp4ztT5xiazwtTP9jqbj7P4xKfZWVrG9tsPv+bruP1taaV
s1ls87IC4f0DnLBssuxdmtERh5W19WG81nl5Hx26Kj7c0j68MdW9qUbluqRNfsOzazCf4Wswi8bh
yXBQVxqizH4a7I3V7gbP7yGxe/ijvvuQLt4XtamW2LIfHYcHsyfiCf3gzWIrjdvXVaU36oL+3j8Y
qp3PhbWZ0YUKez9J7L3wG2auM70x1X4YTXfP3VHrDqPBm7KphZv9/i6hp+ziZxPXw99np7epi21R
YIMQ7Ha3zO+KEb0kxlE0PdkRQ2aCN0lageZbXetnuP6jrDEXE/W8K+xHR2enL3ARZ9aZfVdXabGC
WP7HB7tKC0VRYhuhffQi7eOT6AUHidcmvrtN47tPZaJr4/ZTGGsFY4RhdDxUiW0WmVFdFB6NzqaT
iE+bvixJNH7hNMTqHcfS3vGLu6Oz49/YfV3ZGAFpKyFz8hKZ8HTyksiu1lUt20+/9Qn++RE/96fh
S2J8+QL7wgxNXO//TTtziczkPlidvODETZ1mbj7/qNMCVlv1VnlbPs0nf2y4zBo4gjs8GPzj63Bg
/oP58XenOvApXA9mS505MxzENjHEdTQen4LGvKZ/viqDSfUr9mL8rBuf16/ag1NbfDD3JlPnavxa
HR6+tQoSq3ZalZL6WNZK1WuDfzGxtlnCVMNxn+rSVrG52RQxyMG65rWsCbccyUCEAfk16abS5f5f
egR0kai/vErz3CQp4oq/X9Xr1AVvvGovtyJcOGw58IKGR32Wau3uwE1hHlS7gS1gklvM7L8q74ag
q6sVpMSvXb0ceBGmT2gyG9hxQ3SaDOFygLDwH8yMEKfDWwrHz5slPOlTLu+QUVqfeJGZ02+ZWVSI
nhj13dcq8tEFfn4jYKfRltjZjnGi1qL+M2xtFUV+4jaFX67cbPaq5AT7vdgDw5IdbCkr9v0RkRjZ
0zvq6IlOSyTINFbLpohrCKpelKQXOIqlkvr7Kk1MAe9JTeWkZPWEhOU5QA7kRLGBKD5qFc+OR4pP
3VVBcZSQJ339E078CSf+hBN/wol/AU4MBytTmEpnVJkLTe3YgBJ5tckgLf5LmR1j4WiM70WToqjO
xqjt3nXRvYWT4UCXKRZNRuPROLj4cP3dxRSrV2mNwfHv/IMNlb7L0gXtGZ3yeU3LUVo0j4pSuYpG
x6NJFBydBuW9Ucg0Nx+v1bsqVW9NrKKJCsezKJpNj9Tl1a2imqYeT4+/HB+BGnVrs8EJmIzw9U9T
JC3PMvnFuvYsDPBHxh8dlsHQT1BZqSvwhQzlv53vBitbmqpODe3cu+6+UNWLZbpSBJ7m1bzYu22M
umhWKkSUzKbjWXgKbm+Y3RNakNs6OZ8347E+WVySzWAD9/Hy+krJ4FE0GsuvJS2X4wPS1R/fVdqq
Po+m0+MpDa5AI0d9OR8zH/oxkPrpzsMxD7lSPxQBWd9wLTwPQhp+WKe1CbLU1ed2yeRNoZEGgl8a
uNK5LXpDFSLBj9DPUYlIQFZMzv+H/8wLXRQWpdb4swMdr1O4ZI4a6vxGFFz7ECyzdLXuThTWdJHm
KKd+nYzldtEOMHoLOjH91rWukthW3Xd5X/r1SbpcpnGT1ZtzFlSipbZV4ExdE8Y4p+GMsI9YAKJk
yXbMGZP0lhBkP3979e7i04dbFqSpbeD0vfHn3afmIUigRw0FnJ/SEDlnlxlGmzwj71KUGYCBybEa
MESwhPxLQUC1zUjBx2v4m7pdG6C5lmOUccM42RZwznqtAaZJ57VaGJUWcdYAYOCH+savidaNzbFz
SQR2aTq9NENlMVM5IgmgZPSd2tim8rRUulRQPEEhOgE6p2qZbYjw98C/LblDtC0aWnfqwRZ/rZUu
S6MrRdrKIWwM+2/AviJkKXI/rE2hmnJV6QQERvOCPFyIzeaF2rtFTwAPxRC4yHSxatApKcJSrDIf
DQ5ITWUW9NN/slJp6yUVPJHi6UYwsK7r0s0OD00xekjv0pIw3chWq0P6OvwAQ36xyy/vb374cjw5
C6IvtA9q7AjN1HxgitV8QAd9XhvSHTVuDtlJURMnCRxmqnThMtTbRKZZm8wp+MAvYAYyaWLu0Quq
NXqRjI2cg7A4/fZIxpsYd+umTiwFiDSOxIwULMUAIhG2LijYFAU3lRKfCdV9qtX/UnRjCUd54Gdm
3FfRxps19mnyUgdYpfwpYirtCanGwQkTgy4iZukurt/7ZpX0tJ0IwNYCTG3JX3E+aelQ90UxrOCu
8AhidbFR3o+w3Gefbnarhr3PKRRtC7iUThKFdkY8j9gkAAF2tGsqTkAK/rYwpA8o3fzSaG6zV+k9
1t7rDIl93x+JbH4A4nIesp6hTBvAmlTNZ5ilk79v8gXV9qXqWjJFCBEBNKL5TzAC+2crJK1aVxYJ
Ei6B1egnOOEon5jgskPVa8pYLQ9mQWN5UyByaAnTvmGXgTwIrso+Im3WBiqAOOzqRccaaVXYeb+k
CKUlFIlDldZ/pXuGinclhmoCe+HOXrUPCWBnFZFGWIbASzljShStlJGrDcfq3zO7gGKdXdZKhuF9
eVpTTsrNSi82gJ0jdSOsjPnw1JF5JdIh00PKjLGyFdUKodPq37FelsDq+KGQmQsmtUSOaE8U80OY
hp12ZSGHvecbhpQ8c8VMBszYTI3nnCo4K9P1g07+y9nPwelvME8V8V9innpsPt+nqo4fT80phBSV
fmQZzw2d2bIUogsXrq5NlVouRxSLjg7kDqTlrou3EEch1STkY7wiQDwYiTRO4xY9eIEIhd4oO7yk
VlEnEE3GGZ5iXZbNueASDUTfNpIlHdEJP1AKoQrHy0ffLiaxJQ8lUGFpYiqEjtVCvIqOZW8nADRp
SrcVczL2crqDZxnyUk9E6pWuFrB/AKieCWKjCHtWq+xOxIrfo/wexG6ui4ZLbp8LwJEGvnAwbHPC
jjN4b5C8uly2uSHfetlI/SD1jr/gEWvbZEnHSIoM8lCoLevkt6pkziHgMZoGllHtveNI+CY3sq/I
7k6oZWXzNsXSXj8f9LNSz6YQwptu1xWe8Z/ePoLO8bop7pzo+6NGgm1yFBe+pWwRHkmjBOZKhGyP
IF/xdDlEFJMLCN80SJtHnr23ViZ2rUa5nwCSUKClrX8IHb/s3yAq158gBko3Iqx3gfYgmuiK9m+S
mhf+gqRDbHyLywWQr6UYf8jV1JB81ycjjjvBo+1lMOeghelKIatwr5+1uvtj7nZroj1UQdjzYSp5
fGzQXSgjm0yPJZlsSywje6pvidiQsBvDD7nEbXkaqe/QrkC954DA8NfL609D7AUHC6SdhzSp15Ks
Oaw78gGTn6kTjwe2SMGxYnpLR+oiQRitdbY8BLYX8JIYuJc/CEfCAEjvtujHYVeUe7R68OjqkWKO
0I/OhhLPdPDntAB4hFhwG8OxRiX+03Vx3QKELVQn7EObHpDi54TTizLwn30ohn7LLJqVmN/6VKmo
SFTs0ObRxI1gHMo51MKPullHHsHQBb38KC1SYiNk2doVEoufdVVQmu7tpO7FJ2ai4gkMVYJyQcJs
V+YakZnDpDUpsWoKuk6jMIY4OYc0KLc5no6DjEWQLgM/toWvAFNv6OoU1VAqJqFllr9FyiwR5UyP
oOfe12Yslse/Th0il9QNIuJwFYvvgJHEbS2IhpZTzEy6GQsUTZ7a9hqmxdGchhJda3Ry99JF0a+u
Eaepjn8NyRHiRteiVYgjDz0teGFQCHficupK9MFcXgsbZ2mpeCec5yP0GWvynNzetxDbNYZCGAHh
qNtcoM+5I0Cexms2FfWqGziAdKYZWyTjzV7pcj/QUhQ2ewrpc0v2c3KE9KtOdEKI3+vEdYcyIdJM
j+9/G7vonWrNLPQCor1FeNLKmravUex1tTTxvNSnvsb5PisGvZqzn98SyBYA7+I+zbi/exKqMXpH
lBFPjFMIwxAohVJGTWkjGnvYQOVL0Ah5BN1l0LiHIK2jPBluAZ70PzeUq8nDF9qZ3mH7IbLkM6cM
VYSJ8LkJU8ejA87YzvS54FCh62pup1uDGlQlOY/8U1TFFxfbGw2qAtz5EmImM+nsQW+c0PZ0eoaS
audzf5vBvDI9Bi5I89kuBhi2q57c/Tx7/8JN2EVukXW4uWKAQfWGy1orG2mFmKTuE1FLPxkvqL0f
GTz0trLfFEYuFRZGSC3MkuoT351RHSP7CG3KB3yj1kMhMCJSBPp5cJvSvYmhPrzc+Dsij046ZMul
Y6ldzapmZfnCtmwyXmZdnW0CymlpLOCCe/GKLmZqZr4V9GdLLbHASqdzw7FMGZAgRwu/di1E6mgt
BFSm9K46S3kvgBidkzzV5PhZVeoKdBK+1+A8CoX6rd4ZRWMTSuJ0bRk08nyyzUpxZrQcwjepvUrx
lg/yeYWyCVlbSg7iBWU4V14sJc19C8F4S19ktRcghPbUqkJN2yple3vQ6mX0rWJ8MXrQKV8E/dIY
qY7wG7+f8wyPBw6OMFOn/y9qpS2bzFPzvwkI7RCeF5wEglIKm1z8Buyf5JnUHMCZCvK0bjT0+Yiq
2kxJB9G6Cz38NeVMnUlbIY7O2Upwg6cFKidjTtpy0wyiU6nzdFA3yGM6X6SIKFniL3vlImgm2Y/u
rGCJtZJRQXTeASUydmEDxUxAt4hPR7oC8WQUOCYtlnbrYmtLfsVHjnqXyoDdzF9hi01OvSRHn4N+
XccoNcd+Wm2nmWGGDHq1qszK30B1d3vUkdAj9d3z0gg/RM49xw/pS8KETby7Gz4hs7MOaHmktO03
eNSWvVvJS7qY5ptSk9mSqvAQqb1c6yGGIQjdBtct/gd+WZoKHVhASbog7CWTHsE1ZCYEfY+a8q9m
PWTXoM9xteT5NqN6emQqmW5PcDvaERFHZZ4DlFrx+7wDAx7OEUVa3sJwMgvVEzqNMbHf095ujjry
fqJPv1Xib8JFX9PYdt59Jf/0ESuo16LIve9/uL2a0UuEjHHCoq7XN2o+Y9H1KzrZhNuVdNnRQbsK
KbZArIewmZzPzW0niToEGCAaunrUBLfkg0A2+PMmmrW24inkBLq1mqmfGPSi+A/5GusfRFEKUYu/
+i8fLAFdrVX0eMAXKO0jEXcpzxVyRsKMLhw3ZKS5HHZJwaiHXj3W+VRmgH8pelOiDMfVd3vaTL37
cHE7i16fDKdnj+Fw8jgZRq/D1wkQkiT3/boy+EAiPj8dSw2Qr6PpAT80mccayJcaHXoPvgQM6L2Y
khv2Psv4yaz7JUtrM+HX25MA8UBvrPKc2y5ZxICZ694AvV4Uia76Q/5/auu+myrrfS7TDMmgP1D3
H3VXSf8j70+tkfO6h+yfnX/VPuLPfCHPLL3leVxtyro3cHP94YnwRd3ni0AbBOkfX1qXPva//TUX
PzqHI3oh/9Es/V1Nn9Q6t33GHedF1+dtA2Xz67X/paaYCSPSugroGXk6Phqf4Oer93CUE3MSLc+O
z8aL8OjsVIcLcHGijycn8WSiTydhPE6i5fF0ql6B9vWazRH5o2p7ZwpU3L7KP6NDQVpkS0MSjGw0
v0rSpvGPl8dk+bRk/YYTUTDxmXY0vn79P5YTAvI=
===END CRASH DUMP===

**Comment by CortexPE** [comment]
should be fixed now...
https://github.com/LeverylTeam/Leveryl/commit/3bfbd959c74df4f6d684bd99744058561752dfe2
@NycuRO , you still needs to fix the update-pmmp branch :/

**Comment by ghost** [comment]
Fixed for branch.
