### ISSUE TITLE
error on join

### ISSUE THREAD

**Issue by TrialityPE** [LeverylTeam/Leveryl#110]
Error when joining and can't connect.

09:16:55 [CRITICAL] TypeError: "trim() expects parameter 1 to be string, null given" (EXCEPTION) in "/src/pocketmine/utils/UUID" at line 61

**Comment by daniktheboss** [comment]
Can't reproduce

**Comment by TrialityPE** [comment]
add it to a Raw server with no plugin and run it and try and join it won't let you in the server and show that error

**Comment by CortexPE** [comment]
can't reproduce:
https://travis-ci.org/LeverylTeam/Leveryl/builds/259788555#L2250
It works on latest commit
