### ISSUE TITLE
Players Can't Join

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#112]
Players can't join server

/21:58:38 [CRITICAL] ErrorException: "Undefined property: pocketmine\Player::$sessionAdapter" (EXCEPTION) in "/src/pocketmine/Player" at line 3980
01.08 23:58:38 [Server] INFO /21:58:38 [NOTICE] Blocked 72.239.201.92 for 5 seconds

**Comment by BlazedLucario** [comment]
i had that error too. remove the auth plugin use a diff one

**Comment by tbhDequan** [comment]
its not auth

**Comment by CortexPE** [comment]
Can you turn on Debug Mode in pocketmine.yml?
and send me the lines before and after that critical error message

**Comment by tbhDequan** [comment]
/02:13:42 [DEBUG] #4 /src/pocketmine/plugin/PluginManager(744): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\server\DataPacketSendEvent object)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #5 /src/pocketmine/Player(1243): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\server\DataPacketSendEvent object)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #6 /src/pocketmine/Server(2035): pocketmine\Player->directDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #7 /src/pocketmine/Server(2018): pocketmine\Server->broadcastPacketsCallback(pocketmine\network\mcpe\protocol\BatchPacket object, array Array(), boolean 1)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #8 /src/pocketmine/network/mcpe/RakLibInterface(227): pocketmine\Server->batchPackets(array Array(), array Array(), boolean 1, boolean 1)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #9 /src/pocketmine/Player(1250): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\DisconnectPacket object, boolean , boolean 1)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #10 /src/pocketmine/Player(4236): pocketmine\Player->directDataPacket(pocketmine\network\mcpe\protocol\DisconnectPacket object)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #11 /src/pocketmine/Server(2498): pocketmine\Player->close(string , string Login timeout)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #12 /src/pocketmine/Server(2672): pocketmine\Server->checkTickUpdates(integer 1872, double 1501640022.329)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #13 /src/pocketmine/Server(2420): pocketmine\Server->tick()
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #14 /src/pocketmine/Server(2296): pocketmine\Server->tickProcessor()
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #15 /src/pocketmine/Server(1833): pocketmine\Server->start()
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #16 /src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///custom.phar/, string /, string /plugins/)
02.08 04:13:42 [Server] INFO /02:13:42 [DEBUG] #17 (1): require_once(string phar:///custom.phar/src/pocketmine/PocketMine.php)
02.08 04:13:42 [Server] INFO /02:13:42 [INFO] [/69.57.232.194:58652] logged out due to Login timeout

**Comment by CortexPE** [comment]
this isnt the whole debug message...
theres still more.
I can only see #4 and above but not the main error message and #1 - #3

**Comment by CortexPE** [comment]
please paste in the whole error message
