### ISSUE TITLE
Mob drops and crashes

### ISSUE THREAD

**Issue by Galaxy77YT** [LeverylTeam/Leveryl#121]
Mobs like chickens, pigs, creepers, etc dont drop any items. Spawning a flying mob like ghast crashes the server. Zombies drop feathers instead of rotten flesh.

Thank you

**Comment by daniktheboss** [comment]
@CortexPE test please

**Comment by Galaxy77YT** [comment]
Tested:
How to recreate:
1.Spawn a ghast.
2.Try killing it
3.Try relogging
Steps 2 and 3 do not go any ahead than one hit on ghast and building terrain. It shows a lot of errors in console.
Items drops:
1. Spawn creeper,blaze, chicken, pig and some other mobs
2. Kill them
Killing them does not drop any item.
Item drops 2:
1.Spawn a zombie
2.Kill it
Killing a zombie drops feathers instead of rotten flesh.
During this I found another bug that is while using a mob stacker plugin, all stacked mobs die together and drop stuff of only 1 killed mob

Thank you

**Comment by CortexPE** [comment]
MobStacker is a plugin problem :/ We cant fix that for you.

**Comment by Galaxy77YT** [comment]
Thats fine then. 
Hoping that you can fix the other issues ASAP :)

**Comment by CortexPE** [comment]
Working on it.... 😉
