### ISSUE TITLE
Server Crashes when Join

### ISSUE THREAD

**Issue by EinBexiii** [LeverylTeam/Leveryl#124]
**Description:**
- When I join to my server, the server crahes!

**CrashDump:**

                      [CRITICAL] TypeError: "Argument 1 passed to pocketmine\Player::sendPosition() must be an instance of pocketmine\math\Vector3, null given, called in /home/lobby2/src/pocketmine/Player.php on line 2430" (EXCEPTION) in "/src/pocketmine/Player" at line 4589
11:30:43 [NOTICE] Blocked 91.47.95.146 for 5 seconds
11:30:43 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\Player::sendPosition() must be an instance of pocketmine\math\Vector3, null given, called in /home/lobby2/src/pocketmine/Player.php on line 2430" (EXCEPTION) in "/src/pocketmine/Player" at line 4589
11:30:43 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putUUID() must be an instance of pocketmine\utils\UUID, null given, called in /home/lobby2/src/pocketmine/network/mcpe/protocol/AddPlayerPacket.php on line 70" (EXCEPTION) in "/src/pocketmine/utils/BinaryStream" at line 285
11:30:43 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
11:30:43 [EMERGENCY] Please upload the "/home/lobby2/crashdumps/Mon_Aug_7-11.30.43-EDT_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by EinBexiii** [comment]
Leveryl Crash Dump Mon Aug 7 12:28:38 EDT 2017

Error: Argument 1 passed to pocketmine\utils\BinaryStream::putUUID() must be an instance of pocketmine\utils\UUID, null given, called in /home/lobby2/src/pocketmine/network/mcpe/protocol/AddPlayerPacket.php on line 70
File: /src/pocketmine/utils/BinaryStream
Line: 285
Type: notice

Code:
[276] 		//This is actually two little-endian longs: UUID Most followed by UUID Least
[277] 		$part1 = $this->getLInt();
[278] 		$part0 = $this->getLInt();
[279] 		$part3 = $this->getLInt();
[280] 		$part2 = $this->getLInt();
[281] 
[282] 		return new UUID($part0, $part1, $part2, $part3);
[283] 	}
[284] 
[285] 	public function putUUID(UUID $uuid)
[286] 	{
[287] 		$this->putLInt($uuid->getPart(1));
[288] 		$this->putLInt($uuid->getPart(0));
[289] 		$this->putLInt($uuid->getPart(3));
[290] 		$this->putLInt($uuid->getPart(2));
[291] 	}
[292] 
[293] 	public function getSlot(): Item
[294] 	{
[295] 		$id = $this->getVarInt();

Backtrace:
#0 /src/pocketmine/network/mcpe/protocol/AddPlayerPacket(70): pocketmine\utils\BinaryStream->putUUID(NULL )
#1 /src/pocketmine/network/mcpe/RakLibInterface(213): pocketmine\network\mcpe\protocol\AddPlayerPacket->encode()
#2 /src/pocketmine/Player(1211): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddPlayerPacket object, boolean , boolean )
#3 /src/pocketmine/entity/Wolf(56): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddPlayerPacket object)
#4 /src/pocketmine/Player(1039): pocketmine\entity\Wolf->spawnTo(pocketmine\Player object)
#5 /src/pocketmine/Player(953): pocketmine\Player->doFirstSpawn()
#6 /src/pocketmine/level/Level(2940): pocketmine\Player->sendChunk(integer 310, integer 315, pocketmine\network\mcpe\protocol\BatchPacket object)
#7 /src/pocketmine/level/format/io/ChunkRequestTask(96): pocketmine\level\Level->chunkRequestCallback(integer 310, integer 315, pocketmine\network\mcpe\protocol\BatchPacket object)
#8 /src/pocketmine/scheduler/AsyncPool(170): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#9 /src/pocketmine/scheduler/ServerScheduler(367): pocketmine\scheduler\AsyncPool->collectTasks()
#10 /src/pocketmine/Server(2677): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 693)
#11 /src/pocketmine/Server(2428): pocketmine\Server->tick()
#12 /src/pocketmine/Server(2304): pocketmine\Server->tickProcessor()
#13 /src/pocketmine/Server(1836): pocketmine\Server->start()
#14 /src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/lobby2/, string /home/lobby2/, string /home/lobby2/plugins/)

Leveryl version: 1.0 #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux srv47067host-unlimitedde 2.6.32-openvz-042stab123.2-amd64 #1 SMP Mon Apr 17 17:29:21 MSK 2017 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
NoVoid 0.3 by rirititi for API(s) 1.0.0
LobbySystemMG 2 by  for API(s) 2.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 4.0.0
BauServerCloud 1 by  for API(s) 3.0.0
BexCheat 1 by Bexiii for API(s) 3.0.0
MagicWE 0.2.4 by thebigsmileXD for API(s) 3.0.0, 3.0.0-ALPHA6
Rang 1.5.1 by KCodeYT for API(s) 1.14.0
RefreshQSG 1 by  for API(s) 3.0.0
Screenbox 1 by KCodeYT for API(s) 3.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
WorldFixer 1 by CreeperFace for API(s) 3.0.0-ALPHA6
Auth 1 by  for API(s) 3.0.0
RefreshQSGTwo 1 by  for API(s) 3.0.0
MapImageEngine FleetHD by FleetHD for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWwtv4za2/iuEU2CThWVbdmzHKjJAmslsB5t0spPMzr2oFwNaomw2kqiKVBK36H+/5xxSMu08
ms60Fxe4UxSNRZHnxfP4Dqn+2jEyF50oHA+G4XA0Co+6nYxrc1ZVqupEv3bMuoTXnUIZGYtOt5ML
rfkSh06qZZ2LwrCQlVxrkTCjWKniG2FyWYj5vDYy0/P5d7Lg1frKVILnUVTW5sOHt6/3D1hea8MW
gvGCyUIbXsSCqfQxCrigy4o6y9hS3oqiy2KeZcBQFqy/UrnoZ2qxWA/7uor7m/X9Qpg7Vd3087gU
/bJSRsUq658kyWXG16K65DizV65KpgqWwQo2HYCKKTB6IzPU8TnqJFzf1w5J4Xq39nfnw1zk2omG
R+Nux1QcLBz92NkbsM/SZH86OIh+bweCV80O/PDh/JwdgAx74fP83vObc7l4WxhRpSDi/jAc7fBx
0+dznD+fNwLO5zsSBq9EEatE7BPb4QO2du5+OAzD5znsiERKOSP4qyw9phY/idh0P0vkdvFCqUyA
r25+kRKjB0pASEiz7n9UWbo/nuzoYUkHrxJu+CMC/0GpSILDJ804GM122FvZ5nMULnilS35XXKun
TUb0x0/Rn41HT2mn3shKmyukb/d68oBIJm5F1j/H/+4PZ4eDJ0hpUSSnq7q42Zew20sQbRQOumzz
MH7hvn7HTbx6aL3pE4Klqsq56UvVJ+7vxc+10Oaa65v92e6m0or5nHQJXsXe/FPIUwvg+RcJf/RA
eB2vRFJnouqf6HURX4Kr7ocP8oIT2Oo4n0s1n+9qGbxSxanKy0wYqYotF7kS1e22i8yekcPOvmqe
90eT6Y407Vxw80ZoMKOCFB+TLNr6UPgwL1ri+8PJ9BmiOxIEr3Iui+sVZMPke8ErsxDctBs0mY0s
s/BJZofDox1m9k3wCmrkjZN1+OTy0eDwmeWXlYqhxKrK0Rk9RSc8Gk2eoAPFtDJu/SPZgX5ewM/9
cTh4gsSnT7GColzVsdn/jmtxCqBAnyuePJFOXaW5AMueq+XSmwVEZLHcrtN/ZLTM6iXgg/5B5z+/
dTvi/zMu+RxcATazFuxEKc+06HawAKMFh9MJUJubuen3r1dSM/iXx6YGFdYMBATOxmQigAQswRaZ
KpY6Yqgzu1BgohQCVN2Btou1HT0XAByB93A6dYS/KcERQ3bMvjHAIHi1FOYcivb+wbc07cifNnhy
2syfNnpq2tHAnzZ8cloI0+jH0M2vhKmrghXijtTYt9J0mRXe/R26vyNHZUSLf6Pfhw3FMQ2W9SKT
MUvrIsbUyRrPIht9U9cyOaDZ1vq/0u/WYFZkWEIi02zS4BIjOjxw3I9eNH3QTJ+9aPrITZ8NXjR9
2EwPN6aYDZ0pZqNHTQFrrzIFWxGxt0bkNPNwY4bZuOEsk639+zev3A7+9hUnf8XJX3HyV5z8FSd/
xclfcfLjOLnbWYpCVDxDmFdwPN/rYNBV6wx0hb8aXBXGwh7CykUts6QTDQAoujjqRGE46nZ4KWHS
qDfoDYKT88vvT8YweykNDA5e+A8sqPhNJhe4pndE/OpGIlnU90xXt4fTwWS6AkgZ1EUmc2lEkgg2
7E16o2GgSlHc/hIMDoewW4twOOoNA54nk0MG5fjq4hKwaMFOyoqFU/g3Gs6iYcgurv7JhgMYuT+a
fJocAlM8mYs6U9BlBE+/QLJsVLMvPyndiAQD9JDRQ4ufNRrzB/VvJRPPrG7At6plwWuzUpVGnFLJ
SkI5kbgxZNMf0fLAGZ5FwRfQMXQicCHA5okAdRNcBe+0Ss1rfwDjERg09OZzy926E4J+8Dt4f/nu
6vrju/fnr2HoTiw0GLQTYZcCupyjs1ytNaCvi3/47rE17qsz3FJmo8LQGc/zj8n243T78Wj7cbb9
GO7QCkN4PvwSM51BprpQufoj5vmO1zayTzNV+/u882Irip4w0OhLhN/mh4Vth/9LlBH3pyvI2b4a
zdDTCuAcKX1n/TJFHEeoWYCp3E9PjBfoccGXMv545qnRjGyH3bB3uK2JWYmFXOoc+ub/ev1AoR3X
/Uz9nCi7TnZ1ffL++sPlI9q858XSU4Uet5PyuLezI/88hV7gv6+38kd4+Pl74uhZmbFJIBFesBPv
RVoJvfrXlZ86vMG/PCw2vEBsn+8LhL+KKyGKhbr3ZN+MPRMQD83/RTq01veZv0D+U2imqnO+9L1n
M7btQrayezqcA2grknfpxenl2Z9Vh1rmAOkJ8fyOHp2VMaWO+n3AEKt60YtV3vfl6m+0AXU/qipL
3sh7UXn6eoPPbNgp2LUU1Rs8J9jZtC+M9g1/7A09WV6wfycgoKcKPf7lAYNcIPVaXn8owq/v1KNB
juP/i3EO7PxQt9xfVDTKtzlfirNiSUehXu3YeuGr8iYTwnz/etuZmsFnkU+4/TjcfhxtPx5uP47/
pErkBMWs7mu4+/wS8yHo5RXYy4hmVzWhjx60CBBZRgpEyHuX7RM7VUUqlwzPqOfVvNgjWF4vGaDy
YTScRuMZO3t9Tagc3+fKJMfzejDg08z+Se0f5RoV+1TZP5xdnEaXZ8xCoOYVkLFSBaWqzHE4C0dD
HLxbgSZBJrU5VmmKI7woVF3EIijtaQmPVxLY4C2BPlYFUcIzmAA7IEFnlcfhhOTk926RPh4OiBae
egdpJperlr5dzAuZ82ybYK4WzcAS7JlD6j8mMqmqQJ52zBFa8SqJVdU+l7elW53INJVxnZn1cUjU
qMMzqgq0MAa6QX2Mw3RiEaCrH99hftqMaSESbwrenxy/Pntz8uH8GketxwU/12B8x9INVdDhNvLg
7x7eqgDx5Pjv9A+YpDYq0PxWuIW3UtwFibR3J8dHOIRdVtsG99Z5hu7DEH+wmDynBmXwiBgdiIFx
2Kb9Di4uwaHY9UpowRptGa8EA4DHVAHeZ1bcsBi3ma5uZBFndWIvYh44LtK6gsYZL3XMQ5qap6LL
FLypNJJki0rwG7ZWdeVoMZky2DSZSuIA+1WBz2RrJPyDuGvJ9RORctgxze5U8TfDeFlCfWNorRyU
jemiBVTGY26r991KFKwulxVPgEBvXqCHW2LRvGB7eBgDng1DIEUGsK2GsGZ4Ukwmc9GgJTxnCujL
X8iouBTwduy02F4IAjR1WRS9O3kjS5FI3lPVso9P/XPYyE8q/fT26t2nyWgWDD/hOjBjSyhic8hY
y3kHGX1cCbQdXrrhmSQDLd15BWxTxQudcWPv5Jw1SVKQA34JQ1uaiFsZC7biRZLRJudA2AbMhiXd
ZsG4XtUmURhq9gYQhXEnb3GmtEisWCcYtgyTAp6cuJae3UrO/oUuD1PI9QP3JmKYeXHh1QrWcfRS
rUAax8VuFXeEWK3BCSFLgyOQdieXb2Em1JAE7bR5EYBYCxBqQ/6MgqyhAxozjH8G7goegaIu1sz5
EUx3Idm+3Zhh76MEQ6sCXIonCYNyaT0PxcTzMhCH67qinIc3fQuB9gCji59rnuF20BUmu+VZLdi+
Ywn5+gCIW36QCgRm2gB2E4+uIniLnH+o8wUeZKWMjiXxJJLh8SwEUA/ff8A7WPTPRkmctaoU5GRw
CTy37DJKVswlNXDZLpghB6tpLM1kFqhQOJbXBUQOTiHaV+QyeHNZgpD3kICNwOtLZV29aEVDq1px
3qYYoTgFI7HLpPkbWM5UtCoRmP/JC3fWsn3QAPaZDdEipEPgtIyIEkYrZvNqTbH6j0wtwLBYrZkd
ZnS4hTkpF0u+WBsQiF1ZUQbEXGrcXhvpoNOdJMHI2AyrjqXT2F+TXVJZ0V01ZPWCSAFUEg1Hu/2g
TE1Ou1Sgh8LQQJsBnyUJGZBgERvMKVVQVjZ07vt/XHxEPs8Ij9X0i4TXRpXE36WqVh5HTTMIKfuR
QSMN8mxECgfDQyvVpaikonKEsaiRYUwJ2UnXxlsIrCDVJOhjNCOAeBA20iiNqwISGEQo2A2zw1Nm
teYEJJRRhsdYt9PmVHCRBkTfJpJtOkIO7zCFYIWj6b2Hk1Fth0/BhKWIsRBqMgvKam1s17YKgCVF
qTdqjgZOT33wqEBO65HVesmrBex/4K46IPYxwh61KrkTiuLWMLcGYjfnhf22wZcC4EgNvnDQbXLC
jjM4b7B5NU2b3JBvvKzH3tl6R0/gEStVZ0kriIQMclewjejot6wkyUHByWBgdWR7bygSHuRG8hW7
ulUqrVTepFhc694Hflby9hSUcFu36wqP+I+3DsEv3dJpa+8LDgm2zqG4FHi/0SA81IZZkGwjZMMC
fcXRpRBhRC5AfFND2jx04r1W9sXurmHuR4BkKeDUxj8sHTftT1CV6k8QQ2MgrLLOBRpG+KIt2s+S
mhfudrJFbOARmS2AC7yeJPxBV5QarziZS0YUdxaPurc2By1EWwrJhHt+1mreMGqaDNLusiD0fBhL
HrENTCMKZJPxxCaTTYmlrgDrW2L3ELEbwQ9cC4NOph77HhofMO8xQGDw19PLD11YCxIsIO3cycSs
bLKmsG7JB0Q+YlOHBzZIQZNhvKk9dpJAGK14lvYB21vwkghwL8cIWDLsYHGHvThsi7JHy4NHZ/cY
c4h+eNa18YyMP8oCwCOoBW4jKNawxH+4LC4bgLCB6oh9cNEdpPg54vSiDNyjD8WgVxOLemm3X7lU
ybBIVOTQ4l7EtcU4mHPwLqrXvtXoEQRdylXZk4VEMULSrZlhY/EjrwpM095K7F5cYkYqjkCXJVAu
UJnNzJxDZOawpQaNWNUF/k8AGMZ0040hDZSbHI/sQMcikGngxjbwFcDUKxYiiHIVE9Ey6d8gZdII
c6ZD0HPnaxGp5fCvZn3IJaaGiOgvY+s7IEiiNzsIzTClmMh2MwpQNHpq02uIBkdTGsLPRqCTu7Vd
FP5qe3981crPQXMIccGNtSqoY7+Sa8ALgUJwJyqnuoQemsproeJMloxWgvNcgD1jjp6Tq9sGYuta
YAhDQGjsNhfQ59wgIJfxirYKe9U1OIDtTDPakYwWO6Pbk4aGohXTM4gvLe6ftixsv6qtTRDxO5vo
likRQst4cv9p4tInkySCFxDNCcRWKyuavobZ7ytsE09TXeqrteuzYqBnKPu5JYFdAsC7uJUZ9Xdb
oRpD7whlxBGjFEIwBIyCKcNg2hgOHGzA8mXRCHoEnmXguIMgjaNsDTcAz/Y/V5ir0cMXXAuP2T5+
+fgIly7DrxPDx14IE/cOKGNr4UtBoXKNlLGdbjZUQFWy/NA/rano4GJzooFVgDpfRMy4TTy742tt
aTs63kbZaudyf5PBnDEdBi7Q8tkuBug2s7bOfh49f6Em7CRXkHWouSKAgfWGylqjG1oFhcTuE6IW
fxJeYHvvCTx4S8lvCmEPFRbCklqIFOsTncJhHcP9sbQxH9DZnIdCYBMhRUA/D9JKPDcR2IeXa3dG
5NBJi2ypdKRcGzI1GcsVtrTOaJrSJlsHmNNkbMEF9eIVHswYEr5R9CeFLbGFlZrngmIZMyBCjgZ+
7e4QmqPZIUBljO+as7Sfx4AarZNsW3LwqCl5BXQSOtegPAoGdUudM1qLjTCJ4wFoUJeQT4WXlWK8
w7HuhYctXqV4TYxcXsFsgrttSw7EC5ThnDm1mG3uGwhGS3yV2V4AIbTHlhXUtI1RNqcHjV16Dw3j
itEdl3QQ9HMtbHUEv3HrKc/QeKDBESJ29FnUSlXWmaPmfiMQ2iE8LygJBKUtbPYIOSD/RM/E5gCc
qUBPa0dDl4+wqkXMdhCNu+AHl3UZsZltK6yjU7ayuMHRAirTASVte2YNRMe2ziOjdpDGeL6QEFF2
ijvstQdBkc1+eGYFO7FidtQiOueANjJ2YQPGTICniNsjbYHYGgUcI4tUbVwMPxWKLMued6gMsJvk
K1SxzrGXpOjTYF/dCorNsXvNNq9JYIIMfLmsxNKdQLVne9iR4FfHN49rY+VBcvoxedBeNkxoi3dX
g0/Yt1ELtBxS2vQbNKpK71TyFA+m6aRUZKrEKtyF1F6ueBeGQRE8DTYN/gf8kooKOrAAk3SB2Mu+
dAiuxm2CoPeoMXcr5iG7GvocbWyebzKqo4dbZV83HPSOdayKvTLPAZQq6/d5CwYcnEOKOL2B4bgt
WE+QG2Fit6Y53ey15N0Ln35jxGfhoqtptHfOfW3+8RErUDfWkHs/vLs+i/Amwo5RwsKu1zVqLmPh
8St0sgm1KzJt6UC7ClpsgJiHsImcy81NJwl1CGCAtdDZPUe4ZR8QZIN8bouiZq/oFeQEPLWK2I8E
eqH4d+kY6z9I0RaiBn/5Nx+kAR6tVXh5QAcozQUTdSmPFXJCwoQuNDVkaLkc9kWCoA56eaITVxKA
fjG8j8IMR9V3wy1ib85PrqPht9PueHYfdkf3o+7w2/DbBBCSTe77phLwAIn4+Ghga4B9Ohwf0EWT
uDeAfLHRwWvfU4AB3qd/6IbeYxlvvdU/Z9KIEX1ONA0gHvBjQfv5YjNlEQPMXHkDeHtRJLzyh9z/
ndQ+11XmPaYyM8Kfnxr/68Rl4j/k/qsV5Lz2w82ftPva45Ae84W9ZvGm53G1Lo03cHV5vqV8YXy5
ELSBIj77Uml57z+7Yy76ejLs4d31e5G6sxqf1CpXvuCa8qL2ZVuDsekzTPeLjeFNOESrswAviseD
w8EUfn7zFhwlHc/EYjqZpiKc8slkOhsfzRbjeDCdJLOUHx0lo+QQoM6AfQO0L1e0HXhRj1fxRt2I
Aiqub/KP0KFAWrTfa9KsNadbSbrdf3+KHy/+Ikv7Nc3IGhjllC2N3377H7azu1w=
===END CRASH DUMP===

**Comment by TacosYum** [comment]
Use a different map

**Comment by EinBexiii** [comment]
Thanks, It works :D.

**Comment by EinBexiii** [comment]
Wow, but it is all My Worlds...

**Comment by TacosYum** [comment]
If you use a Minecraft Land Generator (MLG) to generate Terrain try disabling mobs in server.properties

**Comment by TacosYum** [comment]
It's a entity issue
