### ISSUE TITLE
Enchantment Issue

### ISSUE THREAD

**Issue by Galaxy77YT** [LeverylTeam/Leveryl#125]
Found a new issue in the latest update.
/enchant command shows an error when used to enchant an item.
Has been tested
How to reproduce:
Take any tool and try enchanting it using the /enchant command.
An error occurs saying the following statement in chat "An unknown error while attempting to run this command".
Previously only Protection (ID:0) enchantment only was possible.

Thank you :)

**Comment by CortexPE** [comment]
Doesnt occur on me...
![image](https://user-images.githubusercontent.com/17762324/29070828-8081abdc-7c06-11e7-8f59-08be460ff79e.png)

**Comment by tbhDequan** [comment]
AdvancedKits enchant support stopped, please fix

**Comment by daniktheboss** [comment]
plugin issue

**Comment by tbhDequan** [comment]
but in the older version of leveryl it worked why should you change it?

**Comment by daniktheboss** [comment]
did you try on pmmp?

**Comment by tbhDequan** [comment]
yes it works on genisyspro, tesseract and pmmp
