### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by TacosYum** [LeverylTeam/Leveryl#126]
Throw your items from Armour and Hotbar and you'll be able to dup it

**Comment by TacosYum** [comment]
I re logged to see if it was still there and it was

**Comment by TacosYum** [comment]
I'll make a video tomorrow

**Comment by CortexPE** [comment]
steps to reproduce pls?

**Comment by TacosYum** [comment]
Step One get blocks or items no more than 2 then throw them they should duplicate 

it takes more than one try

**Comment by daniktheboss** [comment]
Works on me too. Try without any plugins tho

**Comment by TacosYum** [comment]
Yep still worked

**Comment by TacosYum** [comment]
Also I found a water/lava bucket dup

Craft 2 buckets and take water/lava and keep spamming the lava or water and you get alot and once you have them throw out the water/lava bucket bucket so you can place it and it won't glitch out
