### ISSUE TITLE
Server Crash!

### ISSUE THREAD

**Issue by EinBexiii** [LeverylTeam/Leveryl#127]
**Description:**
When I Join The Server Crashes D:.
Whit GenisysPro, pocketmine it works!, pls fix the bug.

**CrashDump:**

Error: Argument 1 passed to pocketmine\utils\BinaryStream::putUUID() must be an instance of pocketmine\utils\UUID, null given, called in /home/lobby2/src/pocketmine/network/mcpe/protocol/AddPlayerPacket.php on line 70
File: /src/pocketmine/utils/BinaryStream
Line: 285
Type: notice

Code:
[276] 		//This is actually two little-endian longs: UUID Most followed by UUID Least
[277] 		$part1 = $this->getLInt();
[278] 		$part0 = $this->getLInt();
[279] 		$part3 = $this->getLInt();
[280] 		$part2 = $this->getLInt();
[281] 
[282] 		return new UUID($part0, $part1, $part2, $part3);
[283] 	}
[284] 
[285] 	public function putUUID(UUID $uuid)
[286] 	{
[287] 		$this->putLInt($uuid->getPart(1));
[288] 		$this->putLInt($uuid->getPart(0));
[289] 		$this->putLInt($uuid->getPart(3));
[290] 		$this->putLInt($uuid->getPart(2));
[291] 	}
[292] 
[293] 	public function getSlot(): Item
[294] 	{
[295] 		$id = $this->getVarInt();

Backtrace:
#0 /src/pocketmine/network/mcpe/protocol/AddPlayerPacket(70): pocketmine\utils\BinaryStream->putUUID(NULL )
#1 /src/pocketmine/network/mcpe/RakLibInterface(213): pocketmine\network\mcpe\protocol\AddPlayerPacket->encode()
#2 /src/pocketmine/Player(1211): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddPlayerPacket object, boolean , boolean )
#3 /src/pocketmine/entity/Wolf(56): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddPlayerPacket object)
#4 /src/pocketmine/Player(947): pocketmine\entity\Wolf->spawnTo(pocketmine\Player object)
#5 /src/pocketmine/level/Level(2940): pocketmine\Player->sendChunk(integer 309, integer 313, pocketmine\network\mcpe\protocol\BatchPacket object)
#6 /src/pocketmine/level/format/io/ChunkRequestTask(96): pocketmine\level\Level->chunkRequestCallback(integer 309, integer 313, pocketmine\network\mcpe\protocol\BatchPacket object)
#7 /src/pocketmine/scheduler/AsyncPool(170): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#8 /src/pocketmine/scheduler/ServerScheduler(367): pocketmine\scheduler\AsyncPool->collectTasks()
#9 /src/pocketmine/Server(2677): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 169)
#10 /src/pocketmine/Server(2428): pocketmine\Server->tick()
#11 /src/pocketmine/Server(2304): pocketmine\Server->tickProcessor()
#12 /src/pocketmine/Server(1836): pocketmine\Server->start()
#13 /src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/lobby2/, string /home/lobby2/, string /home/lobby2/plugins/)

Leveryl version: 1.0 #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux srv47067host-unlimitedde 2.6.32-openvz-042stab123.2-amd64 #1 SMP Mon Apr 17 17:29:21 MSK 2017 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
NoVoid 0.3 by rirititi for API(s) 1.0.0
LobbySystemMG 2 by  for API(s) 2.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 4.0.0
BauServerCloud 1 by  for API(s) 3.0.0
BexCheat 1 by Bexiii for API(s) 3.0.0
MagicWE 0.2.4 by thebigsmileXD for API(s) 3.0.0, 3.0.0-ALPHA6
Rang 1.5.1 by KCodeYT for API(s) 1.14.0
RefreshQSG 1 by  for API(s) 3.0.0
Screenbox 1 by KCodeYT for API(s) 3.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
WorldFixer 1 by CreeperFace for API(s) 3.0.0-ALPHA6
Auth 1 by  for API(s) 3.0.0
RefreshQSGTwo 1 by  for API(s) 3.0.0
MapImageEngine FleetHD by FleetHD for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6

**Comment by EinBexiii** [comment]
WTF, @CortexPE RLY?!!!, The Bug isnt fixed and You Closed the Issue your serious?

**Comment by XDqrkneZ** [comment]
He fixed it in https://github.com/LeverylTeam/Leveryl/commit/9a76b3cc9a5a891eacdfa7c06027af0f383ac964

**Comment by EinBexiii** [comment]
No! When I Join Server Crashes!
