### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [LeverylTeam/Leveryl#130]
### Issue description
When I set block and place block on this block the block disappears.

### Steps to reproduce the issue
1. use my code
`        $player->getLevel()->spawnLightning(new Vector3($x, $y, $z));
        $player->getLevel()->setBlock(new Vector3($x, $y, $z), new Block(41, 0));`

### OS and versions
* Leveryl Version: 1.0.0
* PHP Version: 7.0.3
* Server OS: Ubuntu
* Game version: PE
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
No errors

**Comment by daniktheboss** [comment]
is auto save on?

**Comment by CortexPE** [comment]
This works for me...
(No issues with setBlock())
