### ISSUE TITLE
Combat Logger Duplication glitch (Works only on Leveryl)

### ISSUE THREAD

**Issue by TacosYum** [LeverylTeam/Leveryl#133]
Hit an alt account into Combat Log then once they log off they die and drop stuff when they  log back in they still have their stuff

**Comment by TacosYum** [comment]
This only works on Leveryl and I used the plugin off of the PMMP forums the one made for the old tesseract API does the same

**Comment by XDqrkneZ** [comment]
pugin issue.. are you using CombatLogger? is so you need to update it

**Comment by TacosYum** [comment]
It's the PMMP version latest

**Comment by TacosYum** [comment]
And it's a issuenonly present on Leveryl

**Comment by CortexPE** [comment]
can you send me the plugin or a link to download it?

**Comment by CortexPE** [comment]
nvm. lemme just test it.

**Comment by CortexPE** [comment]
Reproduced!

**Comment by TacosYum** [comment]
Sorry I was asleep glad you actually got this reproduced though :D

**Comment by CortexPE** [comment]
I'm thinking it's probably because of how PMMP handles it. (A more laggy and delayed way)
```$this->inventory->clearAll()```
sometimes works and sometimes doesn't.
So, my best guess is (step by step):
1. the inv clear gets delayed
2. the player gets killed instantly after the inv clear gets executed (not having to be finished)
3. the inv clear gets cancelled because, the player is... ded.

**Comment by XDqrkneZ** [comment]
just add a line to combatLogger that deletes the player's data

**Comment by NidPlays** [comment]
That would delete other valuable information

**Comment by XDqrkneZ** [comment]
The player's data is their spawn point, inventory and their achievements.. They die so these shits don't matter

**Comment by XDqrkneZ** [comment]
and there's also other way than deleting the player's data
