### ISSUE TITLE
Undefined class constant 'SILK_TOUCH'

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#134]
01:49:02 [CRITICAL] Could not tick level "minas": Undefined class constant 'SILK_TOUCH'
01:49:02 [CRITICAL] Error: "Undefined class constant 'SILK_TOUCH'" (EXCEPTION) in "/src/pocketmine/block/RedMushroomBlock" at line 62

**Comment by daniktheboss** [comment]
@CortexPE

**Comment by CortexPE** [comment]
Doesn't happen on me...
