### ISSUE TITLE
POLL: Should we Rebase And Re-Write everything?

### ISSUE THREAD

**Issue by CortexPE** [LeverylTeam/Leveryl#137]
# Should we Rebase And Re-Write everything?
**This will be rebased from the ORIGINAL [iTX Technologies](https://github.com/iTXTech) [Genisys](https://github.com/iTXTech/Genisys)...**
## Reason:
 - To add back 32Bit Support
 - More Optimized Codebase... (PMMP's code optimization is kindof mediocre)
 - Has a better AntiCheat System
 - Supports ClassicGUI better than PMMP does it
 - Some of the ported Files from Genisys are causing conflicts...
   - Crafting Issues
   - Slowazz Brewing
   - *Some Entity Errors*
 - GeniAPI

## Notes:
 - We will port over the Missing stuff from Leveryl to Genisys in order to still retain the features.
    - ResourcePacks
    - Player Functions
    - Updated Blocks
    - EnderChests
    - *etc.*
 - We will add the missing PMMP Functions, Events & Files (To maintain Compatibility) Such as:
    - Transaction::getTargetItem()
    - *a ton more. *
 - We will add the missing Tesseract Functions & Events To still maintain Compatibility.
 - We will update the Constants, Variable Names, Block Names & IDs to match up with PMMP and keep it Vanilla-Like

***So you don't have to worry about it.*** &nbsp;😄<br />***Just asking for opinions and Suggestions***

**Comment by XDqrkneZ** [comment]
yes

**Comment by asyncthreading** [comment]
yes

**Comment by ghost** [comment]
Yes.. but make another repo.
