### ISSUE TITLE
error when switching softwares

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#138]
etwork\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 73
05:12:54 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 73" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/DataPacket" at line 375
05:12:54 [CRITICAL] Could not tick level "pd": Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 73
05:12:54 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 73" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/DataPacket" at line 375
05:12:54 [CRITICAL] Could not tick level "pd": Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 73
05:12:54 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 73" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/DataPacket" at line 375

i'm switching from pocketmine to leveryl but i get this error when i switch worlds

**Comment by XDqrkneZ** [comment]
now i get new error!

17:07:54 [CRITICAL] Unhandled exception executing command 'mine A' in mine: Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/AddPlayerPacket.php on line 75
17:07:54 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/AddPlayerPacket.php on line 75" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/DataPacket" at line 375

**Comment by XDqrkneZ** [comment]
another error found, why is this happening..


17:10:57 [CRITICAL] TypeError: "Argument 2 passed to pocketmine\nbt\tag\DoubleTag::__construct() must be of the type float, string given, called in /home/pe/src/pocketmine/entity/Entity.php on line 854" (EXCEPTION) in "/src/pocketmine/nbt/tag/DoubleTag" at line 39
17:10:57 [EMERGENCY] Crashed while crashing, killing process

**Comment by daniktheboss** [comment]
Because strict types. You giving a string but need int. Plugin Issue. Tesseract doesn't check this that's why it doesn't happen

**Comment by XDqrkneZ** [comment]
@daniktheboss does leveryl check this?

**Comment by daniktheboss** [comment]
yes
