### ISSUE TITLE
gamemode change

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [LeverylTeam/Leveryl#14]
Inventory don't reset if change to survival from creative. I copy .yml from master and set it to true

**Comment by bioaim4** [comment]
I have a plugin for that if you need it till its fixed

**Comment by TDMidkwhatisxd** [comment]
I don't really need it. I  just like the feature, but thx

**Comment by CortexPE** [comment]
Ok I'll add it whenever I have time... (Since it's related to a few other features)
I'll also work on making GameRules work rather than just implementing the main command...
