### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by juiceluqi** [LeverylTeam/Leveryl#142]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version:
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by juiceluqi** [comment]
Are you ready to play on the cell phone pocketmine?

**Comment by juiceluqi** [comment]
I do not have a computer :(

**Comment by Pizzahaet** [comment]
@CortexPE CLOSE THIS LMFAO
