### ISSUE TITLE
AddEntityPacket not found

### ISSUE THREAD

**Issue by KielKing** [LeverylTeam/Leveryl#144]
I get:
Class pocketmine\network\protocol\AddEntityPacket not found" (EXCEPTION)
When running this plugin, can anyone help? I'm guessing there is no AddEntityPacket in leveryl yet

**Comment by XDqrkneZ** [comment]
no AddEntityPacket in Leveryl? No. Go open the plugin file and remove pocketmine\network\protocol\AddEntityPacket.. replace it with pocketmine\network\mcpe\protocol\AddEntityPacket

**Comment by NidPlays** [comment]
Close please @CortexPE @KielKing
