### ISSUE TITLE
Wow! Rewrite but..

### ISSUE THREAD

**Issue by ghost** [LeverylTeam/Leveryl#145]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

network\mcpe\protocol .. but rewrite with Genisys?! Wow!!

### OS and versions
* Leveryl Version:
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by XDqrkneZ** [comment]
are you stupid?

**Comment by CortexPE** [comment]
packets are moved to make it PMMP's structure
