### ISSUE TITLE
Why do you suddenly restart the project?

### ISSUE THREAD

**Issue by shdudwns** [LeverylTeam/Leveryl#146]
Genisyspro is not optimal, so is not it serious? (Safety is good)
I like the old project

**Comment by shdudwns** [comment]
If you do, how about modifying TESSERACT?

**Comment by shdudwns** [comment]
https://github.com/ServerSoftwareArchiveTeam/Tesseract

**Comment by shdudwns** [comment]
@CortexPE

**Comment by CortexPE** [comment]
Tesseract had it's CORE features removed because of "Touching Code without knowing it's effects"...
