### ISSUE TITLE
Hello! What about optimization? The load is very high! (Translation done by Google Translate)

### ISSUE THREAD

**Issue by LeunPvP** [LeverylTeam/Leveryl#148]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version:
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
Please upload the output of /status, /version and /pl ;)
It'll help A LOT.
😄

**Comment by LeunPvP** [comment]
23 авг 2017 г. 15:53 пользователь "CortexPE" <notifications@github.com>
написал:

**Comment by LeunPvP** [comment]
23 авг 2017 г. 15:58 пользователь "Лайм" <leunpe@gmail.com> написал:

**Comment by shdudwns** [comment]
Is it possible to develop the developer's mine cart to work normally?

**Comment by shdudwns** [comment]
Here you can import the source
https://github.com/BlueLightJapan/BlueLight

**Comment by shdudwns** [comment]
@CortexPE

**Comment by CortexPE** [comment]
@shdudwns Maybe make a PR for it?

**Comment by shdudwns** [comment]
@CortexPE ?

**Comment by CortexPE** [comment]
PR = PullRequest

**Comment by shdudwns** [comment]
Minecart from existing genisyspro has errors
It works under the block, but when I climb the block, the minecart does not work and gets caught in the block

**Comment by shdudwns** [comment]
@CortexPE umm......
I'm poor at developing.

**Comment by shdudwns** [comment]
Help me....
@CortexPE

**Comment by ghost** [comment]
@shdudwns still need a lot of work to activate the Minecart. 마인카트 만들려면 작동시키려면 레일부터 작동시켜야 되요.. 아니다..작동될라나요? 최적화 해야겟네요.

**Comment by CortexPE** [comment]
Due to the lack of information regarding this issue, It will be closed.
