### ISSUE TITLE
Piggycustomenchants error

### ISSUE THREAD

**Issue by moneymill2400** [LeverylTeam/Leveryl#150]
Leveryl Crash Dump Wed Aug 23 14:40:17 AKDT 2017

Error: Declaration of PiggyCustomEnchants\CustomEnchants\CustomEnchants::hasSlot(int $slot): bool must be compatible with pocketmine\item\enchantment\Enchantment::hasSlot($slot): bool
File: /PiggyCustomEnchants-master/src/PiggyCustomEnchants/CustomEnchants/CustomEnchants
Line: 0
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[1] <?php
[2] 
[3] namespace PiggyCustomEnchants\CustomEnchants;
[4] 
[5] use pocketmine\item\enchantment\Enchantment;
[6] 
[7] /**
[8]  * Class CustomEnchants
[9]  * @package PiggyCustomEnchants\CustomEnchants
[10]  */

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Leveryl version: 0918e4f6c9ad224b49cc9b43b8223cd41af1d5b8 [Protocol 113; API 3.0.0-ALPHA5]
uname -a: Windows NT DESKTOP-45C6HM0 10.0 build 15063 (Windows 10) AMD64
PHP version: 7.0.3
Zend version: 3.0.0
OS : WINNT, win

**Comment by CortexPE** [comment]
plugin issue
