### ISSUE TITLE
Error when trying to use live Text

### ISSUE THREAD

**Issue by moneymill2400** [LeverylTeam/Leveryl#152]
15:10:44 [CRITICAL] ClassNotFoundException: "Class pocketmine\network\protocol\AddEntityPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 147

**Comment by XDqrkneZ** [comment]
plugin issue

**Comment by moneymill2400** [comment]
really

**Comment by moneymill2400** [comment]
i just switch to leveryl how can i fix it

**Comment by moneymill2400** [comment]
its not the plugin i cant find that in the file

**Comment by XDqrkneZ** [comment]
replace pocketmine\network\protocol\AddEntityPacket to pocketmine\networ\kmcpe\protocol\AddEntityPacket

**Comment by CortexPE** [comment]
plugin issue
