### ISSUE TITLE
Switch Back please

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#155]
I liked leveryl when it was a fork of pmmp now it's genisys most commands don't work and chest titles :/ Good going

**Comment by XDqrkneZ** [comment]
chest titles?

**Comment by CortexPE** [comment]
You mean the commands don't show up?
There's an option for this on Leveryl.yml
Its something called "display-no-perm-command"...
Just set it to true.

**Comment by tbhDequan** [comment]
no like chest inventorys dont work like playervaults
