### ISSUE TITLE
NPC despawning 

### ISSUE THREAD

**Issue by DroidPlaysM** [LeverylTeam/Leveryl#156]
Spawn a NPC restart the server and it's gone no errors or anything just NPC gone.

**Comment by CortexPE** [comment]
Working on a fix...

**Comment by CortexPE** [comment]
What's your NPC plugin?
Plugin name and version number

**Comment by CortexPE** [comment]
Works for me https://github.com/LeverylTeam/NPC

**Comment by CortexPE** [comment]
nvm.
but this is a plugin error...
NPCs need to be re-initialized on startup
