### ISSUE TITLE
Um ... how about creating a new team?

### ISSUE THREAD

**Issue by shdudwns** [LeverylTeam/Leveryl#16]
Make a new team and collect the developers
There are currently no developers on this team.

**Comment by DerddyDert** [comment]
He is the Lone Coder.

**Comment by CortexPE** [comment]
Everyone is welcome to contribute... ;)
And I don't give anyone write access as it may cause the software to die...
How?
 - Someone may touch the code w/o making sure it works or w/o checking how stable the commit is.
