### ISSUE TITLE
When craften, the items are gone and you lose the items

### ISSUE THREAD

**Issue by ghost** [LeverylTeam/Leveryl#165]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version:
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by tbhDequan** [comment]
issue doesn't happen to me may be its one of your plugin. Try without plugins
