### ISSUE TITLE
what no way..

### ISSUE THREAD

**Issue by pranavbhuv** [LeverylTeam/Leveryl#167]
Am I blind or did you say custom enchants????
Tell me more...
TEACH ME THE WAYS lol

**Comment by XDqrkneZ** [comment]
This is not an issue

**Comment by pranavbhuv** [comment]
How to use custom Enchants

**Comment by XDqrkneZ** [comment]
Stupidity 99%

**Comment by CortexPE** [comment]
Use the discord group for this kind of issues please.
