### ISSUE TITLE
Help Me

### ISSUE THREAD

**Issue by TwistedAsylumMC** [LeverylTeam/Leveryl#168]
**Help Me**
I Was Reading The Features Leveryl Has, And It Said Custom Enchants! I Was Like, OMG NO WAY, So I Downloaded It And I Couldn't Find The Custom Enchants, Saying Custom Enchants As A Feature, Did You Mean PiggyCustomEnchants Works? Someone Please Help Me Out Id Really Appreciate It

**Comment by XDqrkneZ** [comment]
PiggyCustomEnchants only support PocketMine-MP. The owne of the plugin said that himself https://github.com/DaPigGuy/PiggyCustomEnchants/commit/a56731b2212ab62065b10fedd5407e6046465a94

**Comment by CortexPE** [comment]
Use the discord group for this kind of issues please.
