### ISSUE TITLE
Error issue in picture

### ISSUE THREAD

**Issue by Pizzahaet** [LeverylTeam/Leveryl#17]
![screenshot_20170627-014725](https://user-images.githubusercontent.com/20936076/27572579-c9314e34-5ada-11e7-824c-f437b0d372bc.png)
![screenshot_20170627-014419](https://user-images.githubusercontent.com/20936076/27572607-eab5972c-5ada-11e7-92f2-fdd1e6b8fc58.png)
![screenshot_20170627-014413](https://user-images.githubusercontent.com/20936076/27572628-04c274e6-5adb-11e7-9c82-2975d0ac38c2.png)

**Comment by CortexPE** [comment]
ReWritten (Corrected) plugin.yml:
```
name: OpticalCore
description: A Plugin for Pazz
api:
- 3.0.0-ALPHA5
main: Pizzahaet\OpticalCore
version: "1.0.0-BETA"
author: Pizzahaet
website: https://twitter.com/Pizzahaet
```

**Comment by Pizzahaet** [comment]
Oml is it because of my version when I put [] instead of "" lol now I feel bad for making an issue
