### ISSUE TITLE
Respawn bug

### ISSUE THREAD

**Issue by shdudwns** [LeverylTeam/Leveryl#18]
Bug!

**Comment by shdudwns** [comment]
@CortexPE

**Comment by CortexPE** [comment]
Can you tell me the steps to replicate it?
I don't experience any bugs with Respawning...

**Comment by shdudwns** [comment]
In the TSP driver, there is a screen shake.And you can't see the block. Is there any error in the motive?
@CortexPE

**Comment by CortexPE** [comment]
"screen shake" maybe you're on the far lands?
Did you Teleport to a really far place?
http://minecraftpocketedition.wikia.com/wiki/Far_Lands

**Comment by shdudwns** [comment]
Appears to occur when you die in another world
There's no error in your motivation.

2017. 6. 28. 오후 8:36에 "CortexPE" <notifications@github.com>님이 작성:

**Comment by CortexPE** [comment]
weird bug... Lemme try to reproduce it.

**Comment by CortexPE** [comment]
The bug doesn't occur on me... '-'

**Comment by DerddyDert** [comment]
Try killing yourself if you are flying in gm c.

**Comment by CortexPE** [comment]
Nope. Bug doesnt occur on me.
