### ISSUE TITLE
There is an error when going to another world.

### ISSUE THREAD

**Issue by shdudwns** [LeverylTeam/Leveryl#19]
CheongkError? 
Before moving to the world, you can see blocks before moving to the world moved to the world.

**Comment by shdudwns** [comment]
@CortexPE

**Comment by ghost** [comment]
번역기좀;;;  chunk error? (청크유어로드유가 뭔가요)
새롭게 bin파일 설치하고 플러그인 다 뺀 상태에서 실행시켜보세요.

**Comment by CortexPE** [comment]
Known MC:PE Bug...
#BlameMojang

**Comment by GDRGamingzz** [comment]
yeah there is a bug when you go into another world then your mc will crash after doing it

**Comment by GDRGamingzz** [comment]
haven't experienced it on other software tho hmmmm.

**Comment by junkdude** [comment]
its an mc bug and was fixed

**Comment by CortexPE** [comment]
@junkdude yep.
