### ISSUE TITLE
New Blocks

### ISSUE THREAD

**Issue by XxParkerGamesxX** [LeverylTeam/Leveryl#2]
Add all the new 1.1 blocks

**Comment by CortexPE** [comment]
Can u list them down?

**Comment by XxParkerGamesxX** [comment]
Just copy the Blocks Folder from Tesseract they have all of them added

**Comment by CortexPE** [comment]
A.K.A. Skidding... LOL
But I'll consider taking a look at it...

**Comment by XxParkerGamesxX** [comment]
Well looks like Pizza Skids alot of shit but whatever software would be hella good with Pizza in it

**Comment by XxParkerGamesxX** [comment]
With pizza not in it

**Comment by CortexPE** [comment]
Everyone is welcome to contribute... If you'd want to, Feel free to do so.

**Comment by Pizzahaet** [comment]
@XxParkerGamesxX keep my name out your mouth... Bitch you copy and paste like a mother fucker

**Comment by Pizzahaet** [comment]
@XxParkerGamesxX @CortexPE and I skid?
![screenshot_20170619-160214](https://user-images.githubusercontent.com/20936076/27303486-eadf4432-5508-11e7-9603-e90dfa497f55.png)

**Comment by EtchYT** [comment]
Chexk this link... It has all the 1.x blocks

https://gist.github.com/jocopa3/f8c9f9158ede0e9d057781188ba440f5
