### ISSUE TITLE
Add the blocks, items and potions in 1.1

### ISSUE THREAD

**Issue by shdudwns** [LeverylTeam/Leveryl#22]
Add the blur and item and potion in 1.1

**Comment by shdudwns** [comment]
@CortexPE

**Comment by CortexPE** [comment]
what do you mean by "blur"?

**Comment by shdudwns** [comment]
blur-> block
@CortexPE

**Comment by CortexPE** [comment]
check the other branch...

**Comment by CortexPE** [comment]
Btw can you list what was added?

**Comment by shdudwns** [comment]
@CortexPE 
Can you bring me the items and monsters in TSP?
