### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shdudwns** [LeverylTeam/Leveryl#25]
Failed loading /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so:  /PocketMine/bin/php7/lib/php/extensions/no-debug-zts-20151012/opcache.so: cannot open shared object file: No such file or directory                           12:06:23 [CRITICAL] ErrorException: "yaml_parse(): scanning error encountered during parsing: mapping values are not allowed in this context (line 70, column 11)" (EXCEPTION) in "/src/pocketmine/utils/Config" at line 142
12:06:23 [DEBUG] #0 (): pocketmine\{closure}(integer 2, string yaml_parse(): scanning error encountered during parsing: mapping values are not allowed in this context (line 70, column 11), string /root/pm/src/pocketmine/utils/Config.php, integer 142, array Array())
12:06:23 [DEBUG] #1 /src/pocketmine/utils/Config(142): yaml_parse(string #                                    .#     __                           _ .#    / /  _____   _____ _ __ _   _| |.#   / /  / _ \ \ / / _ \ '__| | | | |.#  / /__|  __/\ V /  __/ |  | |_| | |.#  \____/\___| \_/ \___|_|   \__, |_|.#                            |___/   .#                                    .#   Leveryl......... ...... ......  ...# ...... ...... ...... (............ ............)....... ...... : 1..# ...... [W.I.P. (............)].NetherEnabled: true.NetherWorldName: "nether"..# ......... ...... (DevTools ......, FolderPluginLoader).DevTools : true.FolderPluginLoader : true.DeveloperCommands : true...# ...... .......CommandLogger : true.ConsoleOnlyCommands : false.ConsoleOnlyCommandsList :. - /stop. - / op. - / deop.LimitedCreative : true.ConsoleOnlyCommandMessage : "... ......... Leveryl ............... ......... ... .............".#### OP... Leveryl Core... AntiCheat ......... ..........TellOPsPlayerAntiCheatMessages : false..# Emtity remove.AutoClearEntities : false.#### AutoClearEntitiesTimer (...).AutoClearEntitiesTimer : 3.BlockTNTExplosion : false..# Game Mechanics.Criticals: true.FireSpread: false..# .............DisableRakLib: false..# .............ClearInventoryOnGameModeChange: true.KeepExperiencePoints: false.#### ............ Leveryl Core... AntiCheat ............ ......... / .......................VerboseConsoleMessages: true..check-movement: false..# .......DisableServerDotLog : false.DisablePluginAPIVersionCheck : true..# .......Weather: true.Lightning: true.LightningFire: false.WeatherDurationMin: 6000.WeatherDurationMax: 12000.LightningTime: 200.. inventory: . #......... ......... ......... ...... ...... true... ................ ............ ......... vanila fashion (...... ......)...... ...... ......... ...... ...... ................ . allow-cheats: false.)
12:06:23 [DEBUG] #2 /src/pocketmine/utils/Config(83): pocketmine\utils\Config->load(string /root/pm/leveryl.yml, integer 2, array Array())
12:06:23 [DEBUG] #3 /src/pocketmine/Server(1431): pocketmine\utils\Config->__construct(string /root/pm/leveryl.yml, integer 2, array Array())
12:06:23 [DEBUG] #4 /src/pocketmine/PocketMine(499): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/pm/, string /root/pm/, string /root/pm/plugins/)
/

**Comment by shdudwns** [comment]
I think. The problem is pocketmine_kor.yml. You should also deal with pocketmine_kor.yml. And please install pocketmine.yml in Korean when installing during installation. Should not you modify it in server.php?

**Comment by Pizzahaet** [comment]
Dude you need the binaries for php

**Comment by CortexPE** [comment]
I already inplemented multi language configs on server.php
I'll just verify the yaml files when I have time... ;)

**Comment by CortexPE** [comment]
implemented* autocorrect -_-
