### ISSUE TITLE
make addTitle() to sendTitle() and remove /mcpe/ folder

### ISSUE THREAD

**Issue by GDRGamingzz** [LeverylTeam/Leveryl#26]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version:
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by GDRGamingzz** [comment]
all the plugs I made using tesseract cant be useful due to folder locations

**Comment by CortexPE** [comment]
sendTitle() is already implemented...
But I can't change the folder for packets... :/
That'd need a TON literally a TON of files to be modified and changed...

**Comment by GDRGamingzz** [comment]
ok thanks
