### ISSUE TITLE
Thinking about changing the location of the network internal file?

### ISSUE THREAD

**Issue by shdudwns** [LeverylTeam/Leveryl#27]
pocketmine\network\mcpe\protocol -> pocketmine\network\protocol

**Comment by shdudwns** [comment]
@CortexPE

**Comment by ghost** [comment]
이미 많은 파일들이 mcpe\protocol 로 연결되어 있어서  바꾸긴 힘들거 같네요.
Leveryl is already  connected mcpe\protocol . So, I think that will very hard.

**Comment by CortexPE** [comment]
Yes indeed. 
Changing that big folder would also break new plug-ins and plugins made for PMMP...
