### ISSUE TITLE
less entities / mob spawner entities

### ISSUE THREAD

**Issue by GDRGamingzz** [LeverylTeam/Leveryl#28]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version:
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by GDRGamingzz** [comment]
there are less entities than the last software I used and (less mobspawner entities also *not sure*)

**Comment by CortexPE** [comment]
More entities will get added when #24 gets merged... 
Idk why Mob spawners won't work though.
