### ISSUE TITLE
MobSpawners

### ISSUE THREAD

**Issue by GDRGamingzz** [LeverylTeam/Leveryl#29]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version:
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by GDRGamingzz** [comment]
mobspawner block and ids doesn't work on current commit

**Comment by DerddyDert** [comment]
@GDRGamingzz were you the GDR from rumben I knew about a year ago?

**Comment by CortexPE** [comment]
MobSpawners doesnt work on BlueLight, Tesseract nor PMMP...
But I've fixed it via an external plugin.

**Comment by GDRGamingzz** [comment]
kindly try to fix mob spawners asap xD
or try to get some help from somebody to help you on fixing it

**Comment by CortexPE** [comment]
Should I upload the MobSpawners + MobAI plugin I'm using?
(It's public btw... Just a fixed Version.)

**Comment by GDRGamingzz** [comment]
sure why not?

**Comment by BrianZP** [comment]
@CortexPE please do so. It would help the community alot.
