### ISSUE TITLE
Add "no weather"

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#30]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ... add no weather
2. ... can be helpful for older device
3. ...

### OS and versions
* Leveryl Version:  Leveryl 1.0.0 「EXPERIMENTAL」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP Version: 7.0.3
* Server OS: LINUX
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
Just edit the "Weather" value in the leveryl.yml ;)
