### ISSUE TITLE
Can't add multiple enchants on one item..?

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#32]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ... i tried to add 2 enchants on one item but only one registered. No console errors
2. ...
3. ...

### OS and versions
* Leveryl Version: Leveryl 1.0.0 「EXPERIMENTAL」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP Version: 7.0.3
* Server OS: LINUX
* Game version: PE / Win10 
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
This should be fixed by now...
![image](https://user-images.githubusercontent.com/17762324/27953399-3e82bb02-62d1-11e7-96c1-764752dd38b9.png)
