### ISSUE TITLE
can you fix?

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#38]
### Issue description
Write a short description about the issue

make players not able to pickup items when their inventory is full
### Steps to reproduce the issue
1. ... when your inventory is full and you pickup items,  items from your inventory drop, so can you make it players not able to pickup stuffs when inventory is full?
2. ...
3. ...

### OS and versions
* Leveryl Version: Latest
* PHP Version: 7.0.3
* Server OS: Linux
* Game version: PE / Win10 Both
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
K wait.

**Comment by CortexPE** [comment]
![image](https://user-images.githubusercontent.com/17762324/28165438-646a25d6-6799-11e7-82c2-123ffa31e083.png)
![image](https://user-images.githubusercontent.com/17762324/28165444-686ae2ec-6799-11e7-9b04-015d9e84d9aa.png)
It doesn't occur on me.
