### ISSUE TITLE
Can't join if XBoxLive GamerTag has spaces

### ISSUE THREAD

**Issue by bioaim4** [LeverylTeam/Leveryl#39]
Players can't join server when signed into Xbox Live.

**Comment by CortexPE** [comment]
I just tried it, and it worked.
![image](https://user-images.githubusercontent.com/17762324/28168570-1d6eb53c-67a5-11e7-9ec4-047806e958a8.png)
![image](https://user-images.githubusercontent.com/17762324/28168604-409a852c-67a5-11e7-8725-634b1e5e2cd0.png)
You can't login With a GamerTag that has spaces in it (For Now...).
