### ISSUE TITLE
Cauldrons

### ISSUE THREAD

**Issue by SerezhaIvanov** [LeverylTeam/Leveryl#42]
### Issue description
21:47:51 [CRITICAL] Невозможно выполнить такт в мире "spawn": Argument 2 passed to pocketmine\nbt\tag\ListTag::__construct() must be
of the type array, object given, called in /home/srv1/src/pocketmine/tile/Cauldron.php on line 122
21:47:51 [CRITICAL] TypeError: "Argument 2 passed to pocketmine\nbt\tag\ListTag::__construct() must be of the type array, object giv
n, called in /home/srv1/src/pocketmine/tile/Cauldron.php on line 122" (EXCEPTION) in "/src/pocketmine/nbt/tag/ListTag" at line 40
### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version: 1.0.0
* PHP Version: 3.0.0-ALPHA5
* Server OS: Ubuntu
* Game version: PE / Win10
* Game OS: PE

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
Cauldrons aren't implemented yet.

**Comment by CortexPE** [comment]
Should be fixed now.
