### ISSUE TITLE
BinaryStream::putLFloat() Error

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#43]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ... i tried switching from PMMp to Leveryl but i get error
2. ...
3. ...

### OS and versions
* Leveryl Version:                                                                                                                                                                                                    Leveryl 1.0.0 「EXPERIMENTAL」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113
* PHP Version: 7.0.3
* Server OS: linux
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

23:59:28 [CRITICAL] Unhandled exception executing command 'mine a' in mine: Argument 1 passed to pocketmine\utils\BinaryStream::putLFloat() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/DataPacket.php on line 354
23:59:28 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putLFloat() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/DataPacket.php on line 354" (EXCEPTION) in "/src/pocketmine/utils/BinaryStream" at line 188

**Comment by CortexPE** [comment]
Lemme fix that.

**Comment by XDqrkneZ** [comment]
thanks fam

**Comment by XDqrkneZ** [comment]
fixed?

**Comment by XDqrkneZ** [comment]
given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 70
02:14:41 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 70" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/DataPacket" at line 353
02:14:41 [CRITICAL] Could not tick level "pd": Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 70
02:14:41 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 70" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/DataPacket" at line 353
02:14:41 [CRITICAL] Could not tick level "pd": Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 70
02:14:41 [CRITICAL] TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, string given, called in /home/pe/src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php on line 70" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/DataPacket" at line 353
/

**Comment by XDqrkneZ** [comment]
BUMP

**Comment by CortexPE** [comment]
That bug doesn't occur on me...
