### ISSUE TITLE
XPOrb bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [LeverylTeam/Leveryl#44]
09:40:44 [CRITICAL] Невозможно выполнить такт в мире "spawn": Call to a member function addSound() on null
09:40:44 [CRITICAL] Error: "Call to a member function addSound() on null" (EXCEPTION) in "/src/pocketmine/entity/XPOrb" at line 114

**Comment by CortexPE** [comment]
Still need to fix eBottles.
"XP System (Still needs to be Improved)" that's what I meant by "Still Needs to be Improved"
