### ISSUE TITLE
Golden apple and Enchanted golden apple don't work

### ISSUE THREAD

**Issue by SerezhaIvanov** [LeverylTeam/Leveryl#45]
Implements please

**Comment by CortexPE** [comment]
![image](https://user-images.githubusercontent.com/17762324/28202725-49fb16f8-683c-11e7-9025-14e259cb4e30.png)
![image](https://user-images.githubusercontent.com/17762324/28202733-513b214c-683c-11e7-910f-8239ae967e7c.png)
Yes it does.
