### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [LeverylTeam/Leveryl#47]
### Issue description
I create flying text for the player, but after a while it disappears and the same problem I have with the PLUGIN, things are created but also disappear after a while.

Code to create flying text:
`$this->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(288 + 0.5, 73 + 0.5, 181 + 0.5), "", "§l§fМагазин зелий"), [$event->getPlayer()]);`
ItemCase:
https://github.com/ondraczsk/ItemCasePE-PHP7
### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version: 1.0.0
* PHP Version: 3.0.0-APLHA5
* Server OS: Ubuntu
* Game version: PE
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
No errors

**Comment by CortexPE** [comment]
PluginIssue.
