### ISSUE TITLE
Can't throw items inside the inventory

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#48]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ... people cant drop items when in gui mode and inside the inventory
2. ...
3. ...

### OS and versions
* Leveryl Version: Leveryl 1.0.0 「EXPERIMENTAL」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP Version: 7.0.3
* Server OS: linux
* Game version: PE / Win10 tested on w10 and mobile
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
If you're on creative, It's supposed to do that. "LimitedCreative"

**Comment by XDqrkneZ** [comment]
the thing is that I'm not in creative
