### ISSUE TITLE
All beds white

### ISSUE THREAD

**Issue by SerezhaIvanov** [LeverylTeam/Leveryl#49]
![screenshot_2017-07-14-09-38-48](https://user-images.githubusercontent.com/12472255/28203300-c3ed9a40-6881-11e7-88f9-c6672ecbab5e.png)

**Comment by CortexPE** [comment]
That'll be fixed soon.
(Occurs on any Server Software)

**Comment by DerddyDert** [comment]
@CortexPE there is a way to make them the proper color. I'm sure you'll sort it out. Just keep in mind that it counts as 2 separate blocks so you will need some redundant code. When we fixed the colors at first they would revert to white or red when dropped from breaking at the foot of the bed.

**Comment by DerddyDert** [comment]
@SerezhaIvanov in a different spoon we called them "hospital beds" :'p
