### ISSUE TITLE
Nice work this is better than Tesseract

### ISSUE THREAD

**Issue by bioaim4** [LeverylTeam/Leveryl#5]
Just too many errors 
21:18:18 [CRITICAL] Could not tick level "world": Call to undefined method pocketmine\item\ItemBlock::getEnchantmentLevel()
21:18:18 [CRITICAL] Error: "Call to undefined method pocketmine\item\ItemBlock::getEnchantmentLevel()" (EXCEPTION) in "/src/pocketmine/block/Leaves" at line 173

**Comment by CortexPE** [comment]
It's fixed on my PC... xD
I'll upload it later.
(Outside rn)

**Comment by CortexPE** [comment]
Should be fixed now...
