### ISSUE TITLE
items don't drop when die

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#51]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ... you don't drop items when you die but you get to keep them
2. ... players inventory get cleared on join (Nope, it's not one of my plugin)
3. ...

### OS and versions
* Leveryl Version: Leveryl 1.0.0 「EXPERIMENTAL」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP Version: 7.0.3
* Server OS: linux
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

here are my plugins 
PurePerms v1.4.0-INDEV, SlapperRotation v1.0.1, BoostPad v1, SlapperCache v1.0.1, StaffChat v1.1.0, VersionModifier v1.0.0, AdvancedKits v5.1, MagicWE v0.3.0, Slapper v1.3.5, CustomAlerts v1.6, SimpleAuth v1.8.1-dev1, SimpleAuthHelper v2.0.5-dev1, PureChat v1.4.0

**Comment by XDqrkneZ** [comment]
this doesn't happen when im in the normal pocketmine world

**Comment by DerddyDert** [comment]
Is there a setting in the yml for player keeps inventory on death? @XDqrkneZ

**Comment by XDqrkneZ** [comment]
@daddydert nope, I even deleted the leveryl.yml and pocketmine.yml to make sure but it still happens

**Comment by XDqrkneZ** [comment]
video https://youtu.be/hvn9AwkG2dU

**Comment by CortexPE** [comment]
Oh it's a problem with GameRule...
(Cuz normal Worlds have Gamerule nbt tags while ported ones don't.)
I'll fix it when I get home.

**Comment by DerddyDert** [comment]
Interesting... @CortexPE which worrld type would you recommend for importing PC maps?

**Comment by CortexPE** [comment]
Anvil... But I'll fix it by overwriting the GameRules NBT tag if it's invalid.

**Comment by DerddyDert** [comment]
Wow. Awesome

**Comment by XDqrkneZ** [comment]
@cortexpe gl

**Comment by CortexPE** [comment]
So... Can you test weather the bug is fixed now?

**Comment by CortexPE** [comment]
oh wait nvm.

**Comment by CortexPE** [comment]
ok so can u test it now?
(lol took 3 commits)

**Comment by XDqrkneZ** [comment]
08:41:48 [CRITICAL] Unhandled exception executing command 'kill' in kill: Undefined index: showDeathMessage
08:41:48 [CRITICAL] ErrorException: "Undefined index: showDeathMessage" (EXCEPTION) in "/src/pocketmine/level/format/io/BaseLevelProvider" at line 169

08:42:26 [CRITICAL] Could not tick level "New World": Undefined index: showDeathMessage
08:42:26 [CRITICAL] ErrorException: "Undefined index: showDeathMessage" (EXCEPTION) in "/src/pocketmine/level/format/io/BaseLevelProvider" at line 169

**Comment by CortexPE** [comment]
try now.

**Comment by XDqrkneZ** [comment]
wow you actually fixed it!!

**Comment by CortexPE** [comment]
:D
