### ISSUE TITLE
inventory bug

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#53]
### Issue description
Write a short description about the issue

video https://www.youtube.com/watch?v=fc38AZJMHqc&feature=youtu.be
### Steps to reproduce the issue
1. ... can't put items to inventory
2. ...can't drop items when inside the inventory
3. ...this is not caused by a plugin

### OS and versions
* Leveryl Version: Leveryl 1.0.0 「EXPERIMENTAL」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP Version: 7.0.3
* Server OS: linux
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
Welp, We nees to wait till PMMP Releases an Inventory Re-Write. :/

**Comment by CortexPE** [comment]
Or just do it here. LoL

**Comment by XDqrkneZ** [comment]
@CortexPE pretty sure this fixed in api3/blocks
