### ISSUE TITLE
NetherWarts

### ISSUE THREAD

**Issue by ghost** [LeverylTeam/Leveryl#54]
### Issue description
00:31:28 [CRITICAL] Could not tick level "Lobby-1": Call to undefined method pocketmine\item\NetherWart::onUpdate()
00:31:28 [CRITICAL] Error: "Call to undefined method pocketmine\item\NetherWart::onUpdate()" (EXCEPTION) in "/src/pocketmine/level/Level" at line 1217

### Steps to reproduce the issue
1. Start and Join in the Server
2. error
3. ...

### OS and versions
* Leveryl Version: Last
* PHP Version: 7.0.3
* Server OS: Linux (Debian)
* Game version: PE / Win10
* Game OS: v1.1.3

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
NetherWarts aren't fully implemented yet... But, I'll work on it ;)

**Comment by ghost** [comment]
Ok
