### ISSUE TITLE
invetory get cleared when join

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#56]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...title says everything
2. ...not a plugin reason
3. ...

### OS and versions
* Leveryl Version:  Leveryl 1.0.0 「EXPERIMENTAL」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP Version: 7.0.3
* Server OS: linux
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by ghost** [comment]
Du you have a Plugin on your Server?

**Comment by XDqrkneZ** [comment]
no

**Comment by XDqrkneZ** [comment]
if you look at the old issue i posted about items not dropping after death, there's a video when my inventory got cleared after joining when i don't have any plugins installed

**Comment by junkdude** [comment]
its a gamerule issue bro

**Comment by XDqrkneZ** [comment]
and?

**Comment by DerddyDert** [comment]
Did inventory dissapear? Or is it being dropped when you either leave/join the server?

**Comment by XDqrkneZ** [comment]
inventory disappear

**Comment by CortexPE** [comment]
Welp, PMMP Has a LOT of inventory bugs.
In theory, Inventory::clearAll() is being delayed if the player is dead.
