### ISSUE TITLE
Entity Bugs

### ISSUE THREAD

**Issue by vickymaulana** [LeverylTeam/Leveryl#57]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version: latest
* PHP Version: 
* Server OS: Ubuntu 17
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)
[CRITICAL] Error: "Call to a member function getCollisionCubes() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 1611

**Comment by CortexPE** [comment]
Known issue with eBottles.

**Comment by vickymaulana** [comment]
And Enchant Fire Aspect Bug :)

**Comment by vickymaulana** [comment]
Please Add Fitur Maxs Enchant Level

**Comment by CortexPE** [comment]
Can you PLEASE specify the steps to reproduce? It's hard to fix issues if
you don't tell us how you got the said issue.
Help Da Devs Fix Yer Probs.

**Comment by CortexPE** [comment]
>No replies.
