### ISSUE TITLE
Effect error

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#60]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...I get that error in the console
2. ...
3. ...

### OS and versions
* Leveryl Version: Updated one in github
* PHP Version: 7.0.3
* Server OS: Linux
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

07:53:17 [CRITICAL] Could not tick level "faction": Effect duration must be in range of 0 - 2147483647
07:53:17 [CRITICAL] InvalidArgumentException: "Effect duration must be in range of 0 - 2147483647" (EXCEPTION) in "/src/pocketmine/entity/Effect" at line 179

**Comment by CortexPE** [comment]
Plugin issue.
