### ISSUE TITLE
.phar

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#61]
I need a .phar of it please.

**Comment by CortexPE** [comment]
Just follow the instructions on our wiki (on a computer) and do /makeserver
or /ms.
Then you'll get a compiled phar at
./plugins/Leveryl/
Then just upload the phar.

Or you can go to CircleCI (it's on the readme. Just click on [✓PASSED] and
login, after that, Just go to artifacts and download the build's phar from
there.

~ Enjoy
