### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#62]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...can't sprint in spec mode
2. ...can't go up and down in spec mode
3. ...invisible potion doesn't make your nametag invisible

### OS and versions
* Leveryl Version: Latest one on github
* PHP Version: 7.0.3
* Server OS: Linux
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
You can sprint in spectator mode. It's just not that fast. (the vanilla way)
And yes you can go up and down is spectator mode.
And yeah, Invisibility hides your nametag

**Comment by XDqrkneZ** [comment]
you can't go up and down ,-,

**Comment by CortexPE** [comment]
Yes you can.
Do you have any plugin installed?

Proof that it works w/o plugins:
![giphy](https://user-images.githubusercontent.com/17762324/28489523-4e2e93c2-6e8a-11e7-9f2d-02acae5cb2a1.gif)

**Comment by XDqrkneZ** [comment]
but that is on windows 10. try it on mobile

**Comment by XDqrkneZ** [comment]
@CortexPE
