### ISSUE TITLE
[MOBILE] Gamemode spectator Can not fly up and down, always up

### ISSUE THREAD

**Issue by vickymaulana** [LeverylTeam/Leveryl#63]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version: latest
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
Can I get a video of this working? That'd help A LOT.

**Comment by CortexPE** [comment]
got it to work on my own.

**Comment by StormCraftMCPE** [comment]
Spectator Mode on SkyWars Plugins Svilex

**Comment by vickymaulana** [comment]
(https://user-images.githubusercontent.com/28435438/28740283-15e35766-742d-11e7-86d6-1718f2f21c29.png)

**Comment by tbhDequan** [comment]
Issue happen to me too

**Comment by vickymaulana** [comment]
@CortexPE
