### ISSUE TITLE
Hello hello.

### ISSUE THREAD

**Issue by ghost** [LeverylTeam/Leveryl#64]
Hello.

Good job with this Software.
Can i contribute to develop generator branch? :D 

My creations developed on Nukkit, i want that and in Leveryl :D (Leveryl, not other software).

Probably you don't know who get improvment of new generaion on Nukkit: Nukkit/Nukkit#1250
And pull where is accepted: Nukkit/Nukkit#1416

**Comment by CortexPE** [comment]
Check your Emails ;)

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
@CortexPE Please, can you create a new branch "Generator" and can i acces them?

**Comment by CortexPE** [comment]
I'll do it when I get home...
(On a phone rn)

**Comment by CortexPE** [comment]
done.

**Comment by ghost** [comment]
thx

**Comment by ghost** [comment]
@CortexPE 

"You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork NycuRO/Leveryl, so you can send a pull request."

**Comment by CortexPE** [comment]
Oh..... Lemme add you to the repo too..

**Comment by CortexPE** [comment]
Try now...

**Comment by ghost** [comment]
@CortexPE Now work.

I work on Branch in next day, i don't have time now :) Ok? :d

**Comment by CortexPE** [comment]
Kk
I might actually add Chorus fruit (working ones)  and some other 1.0 items whenever I have time.
