### ISSUE TITLE
Strength potions too overpowered 

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#65]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...strength pots can kill you with two hits, even if you are full diamond
2. ...
3. ...

### OS and versions
* Leveryl Version: latest
* PHP Version: 7.0.3
* Server OS: linux
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
Hm.

**Comment by XDqrkneZ** [comment]
what

**Comment by CortexPE** [comment]
Test it now.
I've changed the Damage Modifiers

**Comment by XDqrkneZ** [comment]
still overpowered
