### ISSUE TITLE
Water flow below y:0 and warp back to the max build height

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#66]
![desktop 07 25 2017 - 19 14 41 02](https://user-images.githubusercontent.com/22429870/28600197-b03ec128-716d-11e7-827e-5ee3687ca5bb.png)
![desktop 07 25 2017 - 19 14 34 01](https://user-images.githubusercontent.com/22429870/28600204-bcdaae9c-716d-11e7-9883-dd0ef747f200.png)

### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ... water flow below y:0 and warp back to the max build height
2. ...
3. ...

### OS and versions
* Leveryl Version: This server is running Leveryl-v1.0.0
* PHP Version: 7.0.3
* Server OS: linux
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by CortexPE** [comment]
Easy to fix... I'll fix it later.
PMMP Hasn't fixed it yet lol

**Comment by XDqrkneZ** [comment]
is this fixed

**Comment by CortexPE** [comment]
Yes.
