### ISSUE TITLE
CustomEnchantments

### ISSUE THREAD

**Issue by BlazedLucario** [LeverylTeam/Leveryl#79]
can you give me example code for them?

**Comment by TacosYum** [comment]
He means he custom coded the Enchants not support for them

**Comment by TacosYum** [comment]
Oh wait no nvm here's the code for them 

Potion::registerPotion();
Enchantment::registerEnchantment();

**Comment by BlazedLucario** [comment]
im still a noob on plugin making. im almost fluent in php tho just need example for using it

**Comment by XDqrkneZ** [comment]
@blazedlucario this is not the place to ask something like that, go to pmmp.io forums and ask for help
