### ISSUE TITLE
getColor() on null

### ISSUE THREAD

**Issue by ghost** [LeverylTeam/Leveryl#82]
21:16:03 [CRITICAL] Could not tick level "world": Call to a member function getColor() on null
21:16:03 [CRITICAL] Error: "Call to a member function getColor() on null" (EXCEPTION) in "/src/pocketmine/item/Potion" at line 303

**Comment by CortexPE** [comment]
Steps to reproduce?

**Comment by tbhDequan** [comment]
This error doesn't happen to me, try activating debug and send full error so that they can fix this

**Comment by CortexPE** [comment]
Try registering a new CustomPotion... Then give yourself the potion that you registered.
Then drink it.

**Comment by ghost** [comment]
I don't know how reproduce, i'm watch in console and get this.

One plugin is used and is private. (Spiral DustParticle)

**Comment by CortexPE** [comment]
ParticlesPlus?

**Comment by CortexPE** [comment]
It doesn't happen on me... It's probably a plugin error.

**Comment by ghost** [comment]
@CortexPE My plugin and isn't plugin error.

**Comment by daniktheboss** [comment]
cant reproduce my dust color works fine

**Comment by CortexPE** [comment]
@daniktheboss same

**Comment by daniktheboss** [comment]
close

**Comment by ghost** [comment]
I'm use declare(strict_types) = 1;
