### ISSUE TITLE
getCollisionCubes() on null

### ISSUE THREAD

**Issue by ghost** [LeverylTeam/Leveryl#83]
21:37:10 [CRITICAL] Could not tick level "world": Call to a member function getCollisionCubes() on null
21:37:10 [CRITICAL] Error: "Call to a member function getCollisionCubes() on null" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 1736

**Comment by TacosYum** [comment]
Just restart that should be a quick work around the bug

**Comment by CortexPE** [comment]
Steps to reproduce?
(I'm guessing it has something to do with eBottles.)

**Comment by ghost** [comment]
I don't know how reproduce, i'm watch in console and get this.

One plugin is used and is private. (Spiral DustParticle)

**Comment by TacosYum** [comment]
i got this too now
