### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#85]
I want to enable XBox live to be able to join, could you help me. How do I enable it?

**Comment by TacosYum** [comment]
Enable it on Leveryl.yml

**Comment by tbhDequan** [comment]
@TacosYum yes, but where?

**Comment by XDqrkneZ** [comment]
@lolnova stop the server and go to server.properties and set Xbox auth to true. It might be in leveryl.yml if not in server properties

**Comment by tbhDequan** [comment]
There isn't nothing named XBox Auth, by any chance is it online mode?

**Comment by XDqrkneZ** [comment]
yea online mode @LolNova

**Comment by tbhDequan** [comment]
OK Thanks!

**Comment by tbhDequan** [comment]
How do I enable it? 

in server properties it has
online-mode=0

I Offed server then I made it
online-mode=1

But users without Xbox live could still join, any help?

**Comment by CortexPE** [comment]
Its 'XBoxAuth' in leveryl.yml

**Comment by tbhDequan** [comment]
I don't see that line

**Comment by tbhDequan** [comment]
I don't see that line

**Comment by XDqrkneZ** [comment]
delete your old leveryl.yml... smh

**Comment by CortexPE** [comment]
Then add it.
Add a new line:
```
XBoxAuth: true
```
Its set to false by default.

**Comment by tbhDequan** [comment]
ty
