### ISSUE TITLE
when player places block it disappears

### ISSUE THREAD

**Issue by daniktheboss** [LeverylTeam/Leveryl#86]
when player places block it disappears

**Comment by CortexPE** [comment]
Steps to reproduce please.
And have you tested it without plugins?

**Comment by CortexPE** [comment]
It doesn't happen on me.

**Comment by daniktheboss** [comment]
like the item from hotbar disappears

**Comment by CortexPE** [comment]
Inventory bug.
Inventory needs to be rewritten :/

**Comment by daniktheboss** [comment]
shit
