### ISSUE TITLE
XBoxAuth: true not working

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#88]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue
1. ...
2. ...
3. ...

### OS and versions
* Leveryl Version:
* PHP Version:
* Server OS:
* Game version: PE / Win10
* Game OS: 

### Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is NOT reproducible without plugins, It's probably a Plugin Issue. Please ask the author of the plugin.

### Crashdump, backtrace or other files
Please add a CrashDump to help us resolve the issue. :)

**Comment by tbhDequan** [comment]
It still allows players not logged in Xbox live account join

**Comment by CortexPE** [comment]
Do you have OpenSSL?
You need OpenSSL to verify the Public IDs...
(Gotta make changes on how Leveryl reads leveryl.yml >,<)

**Comment by tbhDequan** [comment]
when can you fix the issue?

**Comment by CortexPE** [comment]
It isn't an issue.
I just remembered that Leveryl can't modify/save the config while running.
Btw. Do you see something like "OpenSSL Extension not found!" Or something like that on startup?
