### ISSUE TITLE
getWeather() on null

### ISSUE THREAD

**Issue by ghost** [LeverylTeam/Leveryl#91]
[CRITICAL] Error: "Call to a member function getWeather() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 1046

**Comment by ghost** [comment]
reproduce?

**Comment by CortexPE** [comment]
steps to reproduce pls?

**Comment by CortexPE** [comment]
and have you tested this without plugins?

**Comment by daniktheboss** [comment]
actually, no response not reproducible

**Comment by ghost** [comment]
this happen when /transfer to otherserver

**Comment by daniktheboss** [comment]
tried, still cant reproduce

**Comment by CortexPE** [comment]
same.
plus. if this error occurs, A lot of functions shouldn't work.
