### ISSUE TITLE
NBT Tag

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#96]
Leveryl Crash Dump Sun Jul 30 22:41:24 UTC 2017

Error: Value 128 is too large!
File: /src/pocketmine/nbt/tag/ByteTag
Line: 77
Type: notice

Code:
[68] 	 * @param int $value
[69] 	 *
[70] 	 * @throws \TypeError
[71] 	 */
[72] 	public function setValue($value)
[73] 	{
[74] 		if(!is_int($value)) {
[75] 			throw new \TypeError("ByteTag value must be of type int, " . gettype($value) . " given");
[76] 		} elseif($value < -(2 ** 7) or $value > ((2 ** 7) - 1)) {
[77] 			throw new \InvalidArgumentException("Value $value is too large!");
[78] 		}
[79] 		parent::setValue($value);
[80] 	}
[81] }
[82] 
[83] 
[84] 
[85] 
[86] 
[87] 

Backtrace:
#0 /src/pocketmine/nbt/tag/NamedTag(40): pocketmine\nbt\tag\ByteTag->setValue(integer 128)
#1 /src/pocketmine/nbt/tag/ByteTag(41): pocketmine\nbt\tag\NamedTag->__construct(string Count, integer 128)
#2 /src/pocketmine/item/Item(1224): pocketmine\nbt\tag\ByteTag->__construct(string Count, integer 128)
#3 /src/pocketmine/entity/Human(535): pocketmine\item\Item->nbtSerialize(integer 14)
#4 /src/pocketmine/Player(4352): pocketmine\entity\Human->saveNBT()
#5 /src/pocketmine/Server(2546): pocketmine\Player->save(boolean 1)
#6 /src/pocketmine/Server(2701): pocketmine\Server->doAutoSave()
#7 /src/pocketmine/Server(2420): pocketmine\Server->tick()
#8 /src/pocketmine/Server(2296): pocketmine\Server->tickProcessor()
#9 /src/pocketmine/Server(1832): pocketmine\Server->start()
#10 /src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/servers/server23711/custom.phar/, string /home/minecraft/multicraft/servers/server23711/, string /home/minecraft/multicraft/servers/server23711/plugins/)
#11 (1): require_once(string phar:///home/minecraft/multicraft/servers/server23711/custom.phar/src/pocketmine/PocketMine.php)

Leveryl version: 1.0 #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux 9ce216e6f23f 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by CortexPE** [comment]
Effect amplifiers should be LESS THAN 128

**Comment by tbhDequan** [comment]
What do you mean? It randomly crashes and it says this eror

**Comment by XDqrkneZ** [comment]
Effect amplifiers should be LESS THAN 128

**Comment by tbhDequan** [comment]
only effect giving plugin i have is advancedkits and it has it speed:120:2 so idk why it crashes
