### ISSUE TITLE
error

### ISSUE THREAD

**Issue by XDqrkneZ** [LeverylTeam/Leveryl#97]
01:21:00 [CRITICAL] Could not tick level "Prison Spawn Hybrid PE": Call to a member function getGameRule() on null
01:21:00 [CRITICAL] Error: "Call to a member function getGameRule() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 4529

**Comment by CortexPE** [comment]
Steps to reproduce?

**Comment by daniktheboss** [comment]
no response
