### ISSUE TITLE
Seems to be a crafting issue...

### ISSUE THREAD

**Issue by BlazedLucario** [LeverylTeam/Leveryl#98]
8:02:16 [DEBUG] Packet pocketmine\network\mcpe\protocol\BatchPacket 0xfe78da933663609aefb12e71eb8f3b258fdcbdec38de2a9e6760e4e2600002664516066e230626060817cc070054ae0991
18:02:16 [CRITICAL] ErrorException: "Undefined offset: 0" (EXCEPTION) in "/src/pocketmine/Player" at line 3562
18:02:16 [DEBUG] #0 /src/pocketmine/Player(3562): pocketmine\{closure}(integer 8, string Undefined offset: 0, string /root/lev/src/pocketmine/Player.php, integer 3562, array Array())
18:02:16 [DEBUG] #1 /src/pocketmine/network/mcpe/protocol/CraftingEventPacket(90): pocketmine\Player->handleCraftingEvent(pocketmine\network\mcpe\protocol\CraftingEventPacket object)
18:02:16 [DEBUG] #2 /src/pocketmine/Player(3999): pocketmine\network\mcpe\protocol\CraftingEventPacket->handle(pocketmine\Player object)
18:02:16 [DEBUG] #3 /src/pocketmine/network/mcpe/protocol/BatchPacket(115): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\CraftingEventPacket object)
18:02:16 [DEBUG] #4 /src/pocketmine/Player(3999): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\Player object)
18:02:16 [DEBUG] #5 /src/pocketmine/network/mcpe/RakLibInterface(148): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
18:02:16 [DEBUG] #6 /src/raklib/server/ServerHandler(103): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 71.48.132.102:58427, raklib\protocol\EncapsulatedPacket object, integer 0)
18:02:16 [DEBUG] #7 /src/pocketmine/network/mcpe/RakLibInterface(85): raklib\server\ServerHandler->handlePacket()
18:02:16 [DEBUG] #8 /src/pocketmine/network/Network(185): pocketmine\network\mcpe\RakLibInterface->process()
18:02:16 [DEBUG] #9 /src/pocketmine/Server(2660): pocketmine\network\Network->processInterfaces()
18:02:16 [DEBUG] #10 /src/pocketmine/Server(2420): pocketmine\Server->tick()
18:02:16 [DEBUG] #11 /src/pocketmine/Server(2296): pocketmine\Server->tickProcessor()
18:02:16 [DEBUG] #12 /src/pocketmine/Server(1832): pocketmine\Server->start()
18:02:16 [DEBUG] #13 /src/pocketmine/PocketMine(510): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/lev/, string /root/lev/, string /root/lev/plugins/)
18:02:16 [NOTICE] Blocked 71.48.132.102 for 5 seconds
/

**Comment by ghost** [comment]
Reproduce?

**Comment by BlazedLucario** [comment]
any crafting from inventory or bench
seems to be an issue in player.php under shaped crafting recipe

**Comment by CortexPE** [comment]
ugh...
we seriously need to rewrite the inventory.

**Comment by ghost** [comment]
Hmm, need ideea. Use crafting from one file ,not code :D
