### ISSUE TITLE
Mobs

### ISSUE THREAD

**Issue by tbhDequan** [LeverylTeam/Leveryl#99]
I have a plugin that stacks mobs, on genysis-pro, tesseract when I use them it will only kill 1 mob and drop their loot but on leveryl it kills all the mobs and drops loot of 1. Can you fix please. Thank you

**Comment by daniktheboss** [comment]
PLUGIN ISSUE @CortexPE GIVE ME ADMIN PLEASE

**Comment by tbhDequan** [comment]
But on other software it doesn't happen, for some reason only on leveryl

**Comment by TacosYum** [comment]
It's a plugin issue tell the plugin creator to fix it

**Comment by tbhDequan** [comment]
kk thanks
